import fs from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
// @ts-ignore - No types available for oslllo-svg-fixer
import SVGFixer from "oslllo-svg-fixer";
import svgtofont, { type InfoData } from "svgtofont";

import type { SvgIcon, Transformer } from "../transformer.ts";
import * as utils from "../utils.ts";

const fontName = "elgato-icons";

/**
 * Transformer that generates an icon font and accompanying CSS from all SVG icon sizes (l, m, s).
 * Icons are named with a size suffix (e.g. `accessibility-l`, `accessibility-m`) to avoid collisions.
 */
export class FontTransformer implements Transformer {
	/** @inheritdoc */
	public readonly name = "Icon font";

	/**
	 * Collected icons and their sizes for font generation.
	 */
	#icons: SvgIcon[] = [];

	/** @inheritdoc */
	public transform(icon: SvgIcon): void {
		this.#icons.push(icon);
	}

	/** @inheritdoc */
	public async finalize(): Promise<void> {
		const svgDir = join(tmpdir(), `elgato-icons-svg-${Date.now()}`);
		const fixedDir = join(tmpdir(), `elgato-icons-fixed-${Date.now()}`);

		try {
			// Create the temp directory for the combined SVGs.
			await fs.mkdir(svgDir, { recursive: true });

			// Write each icon size as a separate SVG file with a size suffix.
			for (const icon of this.#icons) {
				for (const [size, { svg }] of icon.sizes) {
					const filename = `${icon.name}-${size}.svg`;
					await fs.writeFile(join(svgDir, filename), svg, "utf8");
				}
			}

			// Fix SVG strokes to fills (required for correct font rendering), then generate the font.
			await SVGFixer(svgDir, fixedDir, { throwIfDestinationDoesNotExist: false }).fix();

			const info = await svgtofont({
				src: fixedDir,
				dist: utils.resolve("font"),
				css: { fontSize: "16px", hasTimestamp: false, include: /\.css$/ },
				fontName,
				outSVGReact: false,
				outSVGReactNative: false,
				outSVGVue: false,
				outSVGPath: false,
				generateInfoData: true,
				emptyDist: true,
				typescript: false,
				log: false,
				excludeFormat: ["eot", "svg", "symbol.svg"],
				svgicons2svgfont: {
					fontHeight: 1024,
					descent: 64,
					centerHorizontally: true,
					centerVertically: true,
					normalize: true,
					preserveAspectRatio: true,
				},
				website: undefined,
			});

			await Promise.all([this.generateCSharpConstants(info), this.generateXamlResourceDictionary(info)]);
		} finally {
			await fs.rm(svgDir, { recursive: true, force: true });
			await fs.rm(fixedDir, { recursive: true, force: true });
		}
	}

	/**
	 * Generates a C# file with const string fields for all icons.
	 */
	private async generateCSharpConstants(info: InfoData): Promise<void> {
		const csharpFields = Object.entries(info).map(([name, entry]) => {
			const { csharpName } = this.convertIconName(name);
			const hexCode = this.getHexCode(entry, name);

			return `\tpublic const string ${csharpName} = "\\u${hexCode}";`;
		});

		const csharpContent = `// <auto-generated />
namespace Elgato.Icons;

/// <summary>Provides strongly-typed icon glyph constants for the Elgato icon font.</summary>
public static class ElgatoIcons
{
	public const string FontFamily = "elgato-icons";

${csharpFields.join("\n")}
}
`;

		await utils.writeFile(utils.resolve("font", `${fontName}.cs`), csharpContent);
	}

	/**
	 * Generates a XAML ResourceDictionary file from the parsed icon entries.
	 */
	private async generateXamlResourceDictionary(info: InfoData): Promise<void> {
		const xamlEntries = Object.entries(info).map(([name, entry]) => {
			const { csharpName } = this.convertIconName(name);
			const hexCode = this.getHexCode(entry, name);

			return `\t<x:String x:Key="${csharpName}">&#x${hexCode};</x:String>`;
		});

		const xamlContent = `<?xml version="1.0" encoding="utf-8"?>
<!-- <auto-generated /> -->
<ResourceDictionary
	xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
${xamlEntries.join("\n")}
</ResourceDictionary>
`;

		await utils.writeFile(utils.resolve("font", `${fontName}.xaml`), xamlContent);
	}

	/**
	 * Converts a CSS-style icon name from info.json to a C# / XAML key.
	 * E.g., "accessibility--filled-l" -> "Accessibility_Filled_L".
	 */
	private convertIconName(name: string): { csharpName: string } {
		const sizeMatch = name.match(/-([lms])$/);
		const size = sizeMatch ? sizeMatch[1] : null;
		let baseName = size ? name.slice(0, -2) : name;

		// Extract style modifiers (--filled, --color, etc.)
		const modifiers: string[] = [];
		const modifierRegex = /--([a-z]+)/g;
		let match;
		while ((match = modifierRegex.exec(baseName)) !== null) {
			modifiers.push(match[1]);
		}
		baseName = baseName.replace(/--[a-z]+/g, "");

		// C# / XAML key: PascalCase with underscores - Name_Style_Size.
		const pascalBaseName = this.toPascalCase(baseName);
		const sizeUpper = size ? size.toUpperCase() : "";
		const styleModifier = modifiers.includes("filled") ? "Filled" : modifiers.includes("color") ? "Color" : "Outlined";

		let csharpName = `${pascalBaseName}_${styleModifier}`;
		if (sizeUpper) {
			csharpName += `_${sizeUpper}`;
		}

		return { csharpName };
	}

	/**
	 * Converts a kebab-case string to PascalCase.
	 * E.g., "adjust-horizontal" -> "AdjustHorizontal"
	 */
	private toPascalCase(str: string): string {
		return str
			.split("-")
			.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
			.join("");
	}

	/**
	 * Extracts the hex code from the info entry, ensuring it's present and properly formatted.
	 * @throws {Error} If the encodedCode is missing or not a string.
	 */
	private getHexCode(entry: InfoData[string], iconName: string): string {
		if (typeof entry.encodedCode !== "string") {
			throw new Error(`Missing encodedCode for icon \"${iconName}\".`);
		}

		return entry.encodedCode.replace("\\", "").toUpperCase();
	}
}
