import fs from "node:fs/promises";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { join } from "node:path";
// @ts-ignore - No types available for opentype.js
import opentype from "opentype.js";
// @ts-ignore - No types available for oslllo-svg-fixer
import SVGFixer from "oslllo-svg-fixer";
import svgtofont, { type InfoData } from "svgtofont";

import type { SvgIcon, Transformer } from "../transformer.ts";
import * as utils from "../utils.ts";

const require = createRequire(import.meta.url);
const packageJson = require("../../package.json") as { version: string; description: string; homepage: string };

const fontName = "elgato-icons";

/**
 * Transformer that generates an icon font and accompanying CSS from all SVG icon sizes (l, m, s).
 * Icons are named with a size suffix (e.g. `accessibility-l`, `accessibility-m`) to avoid collisions.
 */
export class FontTransformer implements Transformer {
	/** @inheritdoc */
	public readonly name = "Icon font";

	/**
	 * Collected icons and their sizes for font generation.
	 */
	#icons: SvgIcon[] = [];

	/** @inheritdoc */
	public transform(icon: SvgIcon): void {
		this.#icons.push(icon);
	}

	/** @inheritdoc */
	public async finalize(): Promise<void> {
		const svgDir = join(tmpdir(), `elgato-icons-svg-${Date.now()}`);
		const fixedDir = join(tmpdir(), `elgato-icons-fixed-${Date.now()}`);

		try {
			// Create the temp directory for the combined SVGs.
			await fs.mkdir(svgDir, { recursive: true });

			// Write each icon size as a separate SVG file with a size suffix.
			for (const icon of this.#icons) {
				for (const [size, { svg }] of icon.sizes) {
					const filename = `${icon.name}-${size}.svg`;
					await fs.writeFile(join(svgDir, filename), svg, "utf8");
				}
			}

			// Fix SVG strokes to fills (required for correct font rendering), then generate the font.
			await SVGFixer(svgDir, fixedDir, { throwIfDestinationDoesNotExist: false }).fix();

			const info = await svgtofont({
				src: fixedDir,
				dist: utils.resolve("font"),
				css: { fontSize: "16px", hasTimestamp: false, include: /\.css$/ },
				fontName,
				outSVGReact: false,
				outSVGReactNative: false,
				outSVGVue: false,
				outSVGPath: false,
				generateInfoData: true,
				emptyDist: true,
				typescript: false,
				log: false,
				excludeFormat: ["eot", "svg", "symbol.svg"],
				svgicons2svgfont: {
					fontHeight: 1024,
					descent: 64,
					centerHorizontally: true,
					centerVertically: true,
					normalize: true,
					preserveAspectRatio: true,
				},
				svg2ttf: {
					copyright: "Copyright (c) Corsair Memory, Inc.",
					description: packageJson.description,
					url: packageJson.homepage,
					version: packageJson.version.split(".").slice(0, 2).join("."), // svg2ttf requires x.y format
				},
				website: undefined,
			});

			// Fix font vertical metrics for proper Windows rendering
			await this.fixFontMetrics();

			await Promise.all([this.generateCSharpConstants(info), this.generateXamlResourceDictionary(info)]);
		} finally {
			await fs.rm(svgDir, { recursive: true, force: true });
			await fs.rm(fixedDir, { recursive: true, force: true });
		}
	}

	/**
	 * Generates a C# file with const string fields for all icons.
	 */
	private async generateCSharpConstants(info: InfoData): Promise<void> {
		const csharpFields = Object.entries(info).map(([name, entry]) => {
			const { csharpName } = this.convertIconName(name);
			const hexCode = this.getHexCode(entry, name);

			return `\tpublic const string ${csharpName} = "\\u${hexCode}";`;
		});

		const csharpContent = `// <auto-generated />
namespace Elgato.Icons;

/// <summary>Provides strongly-typed icon glyph constants for the Elgato icon font.</summary>
public static class ElgatoIcons
{
	public const string FontFamily = "elgato-icons";

${csharpFields.join("\n")}
}
`;

		await utils.writeFile(utils.resolve("font", `${fontName}.cs`), csharpContent);
	}

	/**
	 * Generates a XAML ResourceDictionary file from the parsed icon entries.
	 * @param info The icon info data from svgtofont
	 * @param useLegacySyntax If true, uses legacy keys with l/m duplication; if false, uses CSS-style keys
	 */
	private async generateXamlResourceDictionary(info: InfoData, useLegacySyntax = false): Promise<void> {
		const entriesMap = new Map<string, string>();

		// Group icons by base name (without size) to find missing l/m variants for legacy mode
		const iconGroups = new Map<string, { l?: string; m?: string }>();

		for (const [name, entry] of Object.entries(info)) {
			const { legacyXamlKey, cssXamlKey } = this.convertIconName(name);
			const hexCode = this.getHexCode(entry, name);
			const key = useLegacySyntax ? legacyXamlKey : cssXamlKey;

			entriesMap.set(key, `\t<x:String x:Key="${key}">&#x${hexCode};</x:String>`);

			// Track l/m sizes for duplication in legacy mode
			if (useLegacySyntax) {
				const sizeMatch = name.match(/-([lms])$/);
				if (sizeMatch) {
					const size = sizeMatch[1];
					const baseName = name.slice(0, -2);
					if (!iconGroups.has(baseName)) {
						iconGroups.set(baseName, {});
					}
					const group = iconGroups.get(baseName)!;
					if (size === "l") group.l = hexCode;
					else if (size === "m") group.m = hexCode;
				}
			}
		}

		// Add missing l/m variants in legacy mode (synthetic entries)
		if (useLegacySyntax) {
			for (const [baseName, group] of iconGroups) {
				if (group.l && !group.m) {
					const { legacyXamlKey } = this.convertIconName(`${baseName}-m`);
					if (!entriesMap.has(legacyXamlKey)) {
						entriesMap.set(legacyXamlKey, `\t<x:String x:Key="${legacyXamlKey}">&#x${group.l};</x:String>`);
					}
				} else if (group.m && !group.l) {
					const { legacyXamlKey } = this.convertIconName(`${baseName}-l`);
					if (!entriesMap.has(legacyXamlKey)) {
						entriesMap.set(legacyXamlKey, `\t<x:String x:Key="${legacyXamlKey}">&#x${group.m};</x:String>`);
					}
				}
			}
		}

		// Sort entries alphabetically
		const xamlEntries = [...entriesMap.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([, v]) => v);

		// must be us-ascii, otherwise XAML compiler will complain about glyphs
		const xamlContent = `<?xml version="1.0" encoding="us-ascii"?>
<!-- <auto-generated /> -->
<ResourceDictionary
	xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
${xamlEntries.join("\n")}
</ResourceDictionary>
`;

		await utils.writeFile(utils.resolve("font", `${fontName}.xaml`), xamlContent);
	}

	/**
	 * Converts a CSS-style icon name from info.json to C#, legacy XAML, and CSS XAML keys.
	 * E.g., "accessibility--filled-l" -> { csharpName: "Accessibility_Filled_L", legacyXamlKey: "icon-accessibility-l-filled", cssXamlKey: "accessibility--filled-l" }
	 */
	private convertIconName(name: string): { csharpName: string; legacyXamlKey: string; cssXamlKey: string } {
		const sizeMatch = name.match(/-([lms])$/);
		const size = sizeMatch ? sizeMatch[1] : null;
		let baseName = size ? name.slice(0, -2) : name;

		// Extract style modifiers (--filled, --color, etc.)
		const modifiers: string[] = [];
		const modifierRegex = /--([a-z]+)/g;
		let match;
		while ((match = modifierRegex.exec(baseName)) !== null) {
			modifiers.push(match[1]);
		}
		baseName = baseName.replace(/--[a-z]+/g, "");

		// CSS XAML key: matches CSS class name format (elgato-icons-{name})
		const cssXamlKey = `${fontName}-${name}`;

		// Legacy XAML key: icon-{concatenatedName}-{size}-{style}
		const concatenatedName = baseName.replace(/-/g, "");
		let legacyXamlKey = `icon-${concatenatedName}`;
		if (size) {
			legacyXamlKey += `-${size}`;
		}
		for (const modifier of modifiers) {
			legacyXamlKey += `-${modifier}`;
		}
		if (!modifiers.includes("filled")) {
			legacyXamlKey += "-outlined";
		}

		// C# name: PascalCase with underscores - Name_Style_Size
		const pascalBaseName = this.toPascalCase(baseName);
		const sizeUpper = size ? size.toUpperCase() : "";
		const styleModifier = modifiers.includes("filled") ? "Filled" : modifiers.includes("color") ? "Color" : "Outlined";

		let csharpName = `${pascalBaseName}_${styleModifier}`;
		if (sizeUpper) {
			csharpName += `_${sizeUpper}`;
		}

		return { csharpName, legacyXamlKey, cssXamlKey };
	}

	/**
	 * Converts a kebab-case string to PascalCase.
	 * E.g., "adjust-horizontal" -> "AdjustHorizontal"
	 */
	private toPascalCase(str: string): string {
		return str
			.split("-")
			.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
			.join("");
	}

	/**
	 * Extracts the hex code from the info entry, ensuring it's present and properly formatted.
	 * @throws {Error} If the encodedCode is missing or not a string.
	 */
	private getHexCode(entry: InfoData[string], iconName: string): string {
		if (typeof entry.encodedCode !== "string") {
			throw new Error(`Missing encodedCode for icon \"${iconName}\".`);
		}

		return entry.encodedCode.replace("\\", "").toUpperCase();
	}

	/**
	 * Fixes font vertical metrics for proper rendering on Windows.
	 * Uses binary patching to avoid opentype.js rewriting the entire font (which doubles file size).
	 */
	private async fixFontMetrics(): Promise<void> {
		const ttfPath = utils.resolve("font", `${fontName}.ttf`);
		const buffer = await fs.readFile(ttfPath);

		// Parse font to get table locations and current values
		const font = opentype.parse(buffer.buffer);
		const ascender = font.ascender; // 960
		const descender = Math.abs(font.descender); // 64 - positive for usWinDescent

		// Find OS/2 table offset in the font file
		const os2Table = this.findTableOffset(buffer, "OS/2");
		if (os2Table) {
			// OS/2 table structure offsets (from spec):
			// usWinAscent: offset 74 (UInt16)
			// usWinDescent: offset 76 (UInt16)
			buffer.writeUInt16BE(ascender, os2Table.offset + 74);
			buffer.writeUInt16BE(descender, os2Table.offset + 76);
		}

		await fs.writeFile(ttfPath, buffer);
	}

	/**
	 * Finds the offset and length of a table in a TTF file.
	 */
	private findTableOffset(buffer: Buffer, tag: string): { offset: number; length: number } | null {
		// TTF header: sfntVersion (4) + numTables (2) + searchRange (2) + entrySelector (2) + rangeShift (2) = 12 bytes
		const numTables = buffer.readUInt16BE(4);

		// Table directory starts at offset 12, each entry is 16 bytes
		for (let i = 0; i < numTables; i++) {
			const entryOffset = 12 + i * 16;
			const tableTag = buffer.toString("ascii", entryOffset, entryOffset + 4);
			if (tableTag === tag) {
				const offset = buffer.readUInt32BE(entryOffset + 8);
				const length = buffer.readUInt32BE(entryOffset + 12);
				return { offset, length };
			}
		}
		return null;
	}
}
