import * as utils from "../utils.ts";
import type { ParsedIconEntry } from "./font-types.ts";

const fontName = "elgato-icons";

/**
 * Generates a C# file with const string fields for all icons.
 */
export async function generateCSharpConstants(entries: Map<string, ParsedIconEntry>): Promise<void> {
	const sortedEntries = [...entries.values()].sort((a, b) => a.csharpName.localeCompare(b.csharpName));
	const csharpFields = sortedEntries.map(
		({ csharpName, hexCode }) => `    public const string ${csharpName} = "\\u${hexCode}";`,
	);

	const csharpContent = `// <auto-generated />
namespace Elgato.Icons;

/// <summary>Provides strongly-typed icon glyph constants for the Elgato icon font.</summary>
public static class ElgatoIcons
{
    public const string FontFamily = "elgato-icons";

${csharpFields.join("\n")}
}
`;

	await utils.writeFile(utils.resolve("font", `${fontName}.cs`), csharpContent);
}
