// Last synchronized: Thu, 02 Oct 2025 11:58:48 GMT

/**
 * Collection of available icons, and their associated metadata.
 */
export const icons = {
	accessibility: { name: "Accessibility", sizes: ["s", "m", "l"] },
	"accessibility--filled": { name: "AccessibilityFilled", sizes: ["s", "m", "l"] },
	action: { name: "Action", sizes: ["m", "l"] },
	"action--filled": { name: "ActionFilled", sizes: ["m", "l"] },
	"action-wheel": { name: "ActionWheel", sizes: ["m", "l"] },
	"action-wheel--filled": { name: "ActionWheelFilled", sizes: ["m", "l"] },
	add: { name: "Add", sizes: ["s", "m", "l"] },
	"add-circle": { name: "AddCircle", sizes: ["m", "l"] },
	"add-circle--filled": { name: "AddCircleFilled", sizes: ["m", "l"] },
	"adjust-horizontal": { name: "AdjustHorizontal", sizes: ["m", "l"] },
	"adjust-horizontal--filled": { name: "AdjustHorizontalFilled", sizes: ["m", "l"] },
	"adjust-vertical": { name: "AdjustVertical", sizes: ["m", "l"] },
	"adjust-vertical--filled": { name: "AdjustVerticalFilled", sizes: ["m", "l"] },
	"align-bottom": { name: "AlignBottom", sizes: ["m", "l"] },
	"align-bottom--filled": { name: "AlignBottomFilled", sizes: ["m", "l"] },
	"align-horizontal-center": { name: "AlignHorizontalCenter", sizes: ["m", "l"] },
	"align-horizontal-center--filled": { name: "AlignHorizontalCenterFilled", sizes: ["m", "l"] },
	"align-left": { name: "AlignLeft", sizes: ["m", "l"] },
	"align-left--filled": { name: "AlignLeftFilled", sizes: ["m", "l"] },
	"align-right": { name: "AlignRight", sizes: ["m", "l"] },
	"align-right--filled": { name: "AlignRightFilled", sizes: ["m", "l"] },
	"align-top": { name: "AlignTop", sizes: ["m", "l"] },
	"align-top--filled": { name: "AlignTopFilled", sizes: ["m", "l"] },
	"align-vertical-center": { name: "AlignVerticalCenter", sizes: ["m", "l"] },
	"align-vertical-center--filled": { name: "AlignVerticalCenterFilled", sizes: ["m", "l"] },
	analytics: { name: "Analytics", sizes: ["m", "l"] },
	"analytics--filled": { name: "AnalyticsFilled", sizes: ["m", "l"] },
	announce: { name: "Announce", sizes: ["m"] },
	"announce--filled": { name: "AnnounceFilled", sizes: ["m"] },
	apps: { name: "Apps", sizes: ["m", "l"] },
	"apps--filled": { name: "AppsFilled", sizes: ["m", "l"] },
	ar: { name: "Ar", sizes: ["m", "l"] },
	"ar--filled": { name: "ArFilled", sizes: ["m", "l"] },
	"ar-check": { name: "ArCheck", sizes: ["m", "l"] },
	"ar-check--filled": { name: "ArCheckFilled", sizes: ["m", "l"] },
	"arrow-bottom-left": { name: "ArrowBottomLeft", sizes: ["m"] },
	"arrow-down": { name: "ArrowDown", sizes: ["m", "l"] },
	"arrow-down-right": { name: "ArrowDownRight", sizes: ["m"] },
	"arrow-down-to-right": { name: "ArrowDownToRight", sizes: ["m", "l"] },
	"arrow-horizontal": { name: "ArrowHorizontal", sizes: ["l"] },
	"arrow-left": { name: "ArrowLeft", sizes: ["m", "l"] },
	"arrow-right": { name: "ArrowRight", sizes: ["m", "l"] },
	"arrow-top-left": { name: "ArrowTopLeft", sizes: ["m"] },
	"arrow-top-right": { name: "ArrowTopRight", sizes: ["m"] },
	"arrow-up": { name: "ArrowUp", sizes: ["m", "l"] },
	"arrow-vertical": { name: "ArrowVertical", sizes: ["l"] },
	article: { name: "Article", sizes: ["m", "l"] },
	"article--filled": { name: "ArticleFilled", sizes: ["m", "l"] },
	"aspect-ratio": { name: "AspectRatio", sizes: ["m", "l"] },
	"aspect-ratio--filled": { name: "AspectRatioFilled", sizes: ["m", "l"] },
	attachment: { name: "Attachment", sizes: ["m", "l"] },
	"auto-scroll": { name: "AutoScroll", sizes: ["l"] },
	"auto-scroll--filled": { name: "AutoScrollFilled", sizes: ["l"] },
	"auto-scroll-decrease": { name: "AutoScrollDecrease", sizes: ["l"] },
	"auto-scroll-decrease--filled": { name: "AutoScrollDecreaseFilled", sizes: ["l"] },
	"auto-scroll-down": { name: "AutoScrollDown", sizes: ["l"] },
	"auto-scroll-down--filled": { name: "AutoScrollDownFilled", sizes: ["l"] },
	"auto-scroll-increase": { name: "AutoScrollIncrease", sizes: ["l"] },
	"auto-scroll-increase--filled": { name: "AutoScrollIncreaseFilled", sizes: ["l"] },
	"auto-scroll-set": { name: "AutoScrollSet", sizes: ["l"] },
	"auto-scroll-set--filled": { name: "AutoScrollSetFilled", sizes: ["l"] },
	"auto-scroll-up": { name: "AutoScrollUp", sizes: ["l"] },
	"auto-scroll-up--filled": { name: "AutoScrollUpFilled", sizes: ["l"] },
	auxiliary: { name: "Auxiliary", sizes: ["s", "m", "l"] },
	"auxiliary-add": { name: "AuxiliaryAdd", sizes: ["m", "l"] },
	avatar: { name: "Avatar", sizes: ["m", "l"] },
	"avatar--filled": { name: "AvatarFilled", sizes: ["m", "l"] },
	"background-remove": { name: "BackgroundRemove", sizes: ["m", "l"] },
	"background-remove--filled": { name: "BackgroundRemoveFilled", sizes: ["m", "l"] },
	"background-replace": { name: "BackgroundReplace", sizes: ["m"] },
	"background-replace--filled": { name: "BackgroundReplaceFilled", sizes: ["m"] },
	backspace: { name: "Backspace", sizes: ["l"] },
	"backspace--filled": { name: "BackspaceFilled", sizes: ["l"] },
	badge: { name: "Badge", sizes: ["l"] },
	"badge--filled": { name: "BadgeFilled", sizes: ["l"] },
	"bleach-no": { name: "BleachNo", sizes: ["m"] },
	blinds: { name: "Blinds", sizes: ["l"] },
	"blinds--filled": { name: "BlindsFilled", sizes: ["l"] },
	"block-quote": { name: "BlockQuote", sizes: ["l"] },
	bluetooth: { name: "Bluetooth", sizes: ["l"] },
	blur: { name: "Blur", sizes: ["l"] },
	"blur-background": { name: "BlurBackground", sizes: ["l"] },
	board: { name: "Board", sizes: ["s", "m", "l"] },
	"board--filled": { name: "BoardFilled", sizes: ["s", "m", "l"] },
	bold: { name: "Bold", sizes: ["m", "l"] },
	book: { name: "Book", sizes: ["m", "l"] },
	"book--filled": { name: "BookFilled", sizes: ["m", "l"] },
	bookmark: { name: "Bookmark", sizes: ["m"] },
	"bookmark--filled": { name: "BookmarkFilled", sizes: ["m"] },
	briefcase: { name: "Briefcase", sizes: ["l"] },
	"briefcase--filled": { name: "BriefcaseFilled", sizes: ["l"] },
	brightness: { name: "Brightness", sizes: ["m", "l"] },
	"brightness--filled": { name: "BrightnessFilled", sizes: ["m", "l"] },
	"brightness-decrease": { name: "BrightnessDecrease", sizes: ["m", "l"] },
	"brightness-decrease--filled": { name: "BrightnessDecreaseFilled", sizes: ["m", "l"] },
	"brightness-increase": { name: "BrightnessIncrease", sizes: ["m", "l"] },
	"brightness-increase--filled": { name: "BrightnessIncreaseFilled", sizes: ["m", "l"] },
	"brightness-off": { name: "BrightnessOff", sizes: ["l"] },
	"brightness-off--filled": { name: "BrightnessOffFilled", sizes: ["l"] },
	"brightness-reset": { name: "BrightnessReset", sizes: ["l"] },
	"brightness-reset--filled": { name: "BrightnessResetFilled", sizes: ["l"] },
	"brightness-set": { name: "BrightnessSet", sizes: ["l"] },
	"brightness-set--filled": { name: "BrightnessSetFilled", sizes: ["l"] },
	bug: { name: "Bug", sizes: ["l"] },
	"bug--filled": { name: "BugFilled", sizes: ["l"] },
	calendar: { name: "Calendar", sizes: ["l"] },
	"calendar--filled": { name: "CalendarFilled", sizes: ["l"] },
	"calendar-today": { name: "CalendarToday", sizes: ["m", "l"] },
	"calendar-today--filled": { name: "CalendarTodayFilled", sizes: ["m", "l"] },
	camcorder: { name: "Camcorder", sizes: ["l"] },
	"camcorder--filled": { name: "CamcorderFilled", sizes: ["l"] },
	camera: { name: "Camera", sizes: ["m", "l"] },
	"camera--filled": { name: "CameraFilled", sizes: ["m", "l"] },
	"camera-flip": { name: "CameraFlip", sizes: ["l"] },
	"camera-flip--filled": { name: "CameraFlipFilled", sizes: ["l"] },
	"camera-frame-preset": { name: "CameraFramePreset", sizes: ["l"] },
	"camera-frame-preset--filled": { name: "CameraFramePresetFilled", sizes: ["l"] },
	"camera-frame-preset-check": { name: "CameraFramePresetCheck", sizes: ["l"] },
	"camera-frame-preset-check--filled": { name: "CameraFramePresetCheckFilled", sizes: ["l"] },
	"camera-frame-preset-reset": { name: "CameraFramePresetReset", sizes: ["l"] },
	"camera-frame-preset-reset--filled": { name: "CameraFramePresetResetFilled", sizes: ["l"] },
	"camera-frame-preset-set": { name: "CameraFramePresetSet", sizes: ["l"] },
	"camera-frame-preset-set--filled": { name: "CameraFramePresetSetFilled", sizes: ["l"] },
	"camera-input": { name: "CameraInput", sizes: ["l"] },
	"camera-input--filled": { name: "CameraInputFilled", sizes: ["l"] },
	"camera-input-check": { name: "CameraInputCheck", sizes: ["l"] },
	"camera-input-check--filled": { name: "CameraInputCheckFilled", sizes: ["l"] },
	"camera-monitor-mount": { name: "CameraMonitorMount", sizes: ["l"] },
	"camera-monitor-mount-alt": { name: "CameraMonitorMountAlt", sizes: ["l"] },
	"camera-off": { name: "CameraOff", sizes: ["m", "l"] },
	"camera-off--filled": { name: "CameraOffFilled", sizes: ["m", "l"] },
	"camera-preview-to-prompter": { name: "CameraPreviewToPrompter", sizes: ["l"] },
	"camera-preview-to-prompter--filled": { name: "CameraPreviewToPrompterFilled", sizes: ["l"] },
	"camera-sensor": { name: "CameraSensor", sizes: ["l"] },
	capture: { name: "Capture", sizes: ["l"] },
	"capture--filled": { name: "CaptureFilled", sizes: ["l"] },
	carousel: { name: "Carousel", sizes: ["l"] },
	cart: { name: "Cart", sizes: ["m", "l"] },
	"cart--filled": { name: "CartFilled", sizes: ["m", "l"] },
	"cart-add": { name: "CartAdd", sizes: ["m", "l"] },
	"cart-remove": { name: "CartRemove", sizes: ["m", "l"] },
	cathedral: { name: "Cathedral", sizes: ["l"] },
	"cathedral--filled": { name: "CathedralFilled", sizes: ["l"] },
	cave: { name: "Cave", sizes: ["l"] },
	"cave--filled": { name: "CaveFilled", sizes: ["l"] },
	chapter: { name: "Chapter", sizes: ["l"] },
	"chapter--filled": { name: "ChapterFilled", sizes: ["l"] },
	"chapter-check": { name: "ChapterCheck", sizes: ["l"] },
	"chapter-check--filled": { name: "ChapterCheckFilled", sizes: ["l"] },
	"chapter-down-to-bottom": { name: "ChapterDownToBottom", sizes: ["l"] },
	"chapter-down-to-bottom--filled": { name: "ChapterDownToBottomFilled", sizes: ["l"] },
	"chapter-marker": { name: "ChapterMarker", sizes: ["l"] },
	"chapter-marker--filled": { name: "ChapterMarkerFilled", sizes: ["l"] },
	"chapter-marker-off": { name: "ChapterMarkerOff", sizes: ["l"] },
	"chapter-marker-off--filled": { name: "ChapterMarkerOffFilled", sizes: ["l"] },
	"chapter-set": { name: "ChapterSet", sizes: ["l"] },
	"chapter-set--filled": { name: "ChapterSetFilled", sizes: ["l"] },
	"chapter-up-to-top": { name: "ChapterUpToTop", sizes: ["l"] },
	"chapter-up-to-top--filled": { name: "ChapterUpToTopFilled", sizes: ["l"] },
	checkmark: { name: "Checkmark", sizes: ["m", "l"] },
	"checkmark-circle": { name: "CheckmarkCircle", sizes: ["s", "m", "l"] },
	"checkmark-circle--filled": { name: "CheckmarkCircleFilled", sizes: ["s", "m", "l"] },
	"chevron-down": { name: "ChevronDown", sizes: ["m", "l"] },
	"chevron-left": { name: "ChevronLeft", sizes: ["s", "m", "l"] },
	"chevron-right": { name: "ChevronRight", sizes: ["s", "m", "l"] },
	"chevron-up": { name: "ChevronUp", sizes: ["m", "l"] },
	"chevrons-down": { name: "ChevronsDown", sizes: ["l"] },
	"chevrons-down-decrease": { name: "ChevronsDownDecrease", sizes: ["l"] },
	"chevrons-down-increase": { name: "ChevronsDownIncrease", sizes: ["l"] },
	"chevrons-down-set": { name: "ChevronsDownSet", sizes: ["l"] },
	"chevrons-left": { name: "ChevronsLeft", sizes: ["l"] },
	"chevrons-left-right": { name: "ChevronsLeftRight", sizes: ["l"] },
	"chevrons-right": { name: "ChevronsRight", sizes: ["l"] },
	"chevrons-up": { name: "ChevronsUp", sizes: ["l"] },
	"chevrons-up-down": { name: "ChevronsUpDown", sizes: ["l"] },
	circle: { name: "Circle", sizes: ["s", "l"] },
	"circle--filled": { name: "CircleFilled", sizes: ["s", "l"] },
	city: { name: "City", sizes: ["l"] },
	"city--filled": { name: "CityFilled", sizes: ["l"] },
	clamp: { name: "Clamp", sizes: ["s", "m", "l"] },
	clipboard: { name: "Clipboard", sizes: ["l"] },
	"clipboard--filled": { name: "ClipboardFilled", sizes: ["l"] },
	clipguard: { name: "Clipguard", sizes: ["l"] },
	close: { name: "Close", sizes: ["m", "l"] },
	"close-circle": { name: "CloseCircle", sizes: ["l"] },
	"close-circle--filled": { name: "CloseCircleFilled", sizes: ["l"] },
	"close-square": { name: "CloseSquare", sizes: ["s", "m", "l"] },
	"close-square--filled": { name: "CloseSquareFilled", sizes: ["s", "m", "l"] },
	cloud: { name: "Cloud", sizes: ["l"] },
	"cloud--filled": { name: "CloudFilled", sizes: ["l"] },
	code: { name: "Code", sizes: ["l"] },
	"code-block": { name: "CodeBlock", sizes: ["m", "l"] },
	"code-block--filled": { name: "CodeBlockFilled", sizes: ["m", "l"] },
	"code-build": { name: "CodeBuild", sizes: ["m", "l"] },
	"color-wheel": { name: "ColorWheel", sizes: ["m", "l"] },
	compass: { name: "Compass", sizes: ["m", "l"] },
	"compass--filled": { name: "CompassFilled", sizes: ["m", "l"] },
	compose: { name: "Compose", sizes: ["l"] },
	"compose--filled": { name: "ComposeFilled", sizes: ["l"] },
	copy: { name: "Copy", sizes: ["m", "l"] },
	"copy--filled": { name: "CopyFilled", sizes: ["m", "l"] },
	couch: { name: "Couch", sizes: ["l"] },
	"couch--filled": { name: "CouchFilled", sizes: ["l"] },
	cpu: { name: "Cpu", sizes: ["l"] },
	"cpu--filled": { name: "CpuFilled", sizes: ["l"] },
	crossfade: { name: "Crossfade", sizes: ["m", "l"] },
	crosshair: { name: "Crosshair", sizes: ["l"] },
	"crosshair-check": { name: "CrosshairCheck", sizes: ["l"] },
	crown: { name: "Crown", sizes: ["l"] },
	"crown--filled": { name: "CrownFilled", sizes: ["l"] },
	cube: { name: "Cube", sizes: ["m", "l"] },
	"cube--filled": { name: "CubeFilled", sizes: ["m", "l"] },
	"currency-dollar": { name: "CurrencyDollar", sizes: ["l"] },
	"currency-euro": { name: "CurrencyEuro", sizes: ["l"] },
	"currency-pound": { name: "CurrencyPound", sizes: ["l"] },
	"currency-yen": { name: "CurrencyYen", sizes: ["l"] },
	cursor: { name: "Cursor", sizes: ["l"] },
	"cursor--filled": { name: "CursorFilled", sizes: ["l"] },
	cut: { name: "Cut", sizes: ["l"] },
	database: { name: "Database", sizes: ["l"] },
	"database--filled": { name: "DatabaseFilled", sizes: ["l"] },
	debug: { name: "Debug", sizes: ["m", "l"] },
	delivery: { name: "Delivery", sizes: ["l"] },
	"delivery--filled": { name: "DeliveryFilled", sizes: ["l"] },
	design: { name: "Design", sizes: ["m"] },
	"design--filled": { name: "DesignFilled", sizes: ["m"] },
	diagram: { name: "Diagram", sizes: ["l"] },
	"diagram--filled": { name: "DiagramFilled", sizes: ["l"] },
	dial: { name: "Dial", sizes: ["s", "m", "l"] },
	"dial--filled": { name: "DialFilled", sizes: ["s", "m", "l"] },
	"dial-press": { name: "DialPress", sizes: ["l"] },
	"dial-rotate": { name: "DialRotate", sizes: ["l"] },
	"dial-rotate-c-w": { name: "DialRotateCW", sizes: ["l"] },
	"dial-rotate-c-w--filled": { name: "DialRotateCWFilled", sizes: ["l"] },
	"dial-rotate-cc-w": { name: "DialRotateCCW", sizes: ["l"] },
	"dial-rotate-cc-w--filled": { name: "DialRotateCCWFilled", sizes: ["l"] },
	"dial-stack": { name: "DialStack", sizes: ["l"] },
	"dial-stack--filled": { name: "DialStackFilled", sizes: ["l"] },
	diamond: { name: "Diamond", sizes: ["l"] },
	"diamond--filled": { name: "DiamondFilled", sizes: ["l"] },
	diffuse: { name: "Diffuse", sizes: ["l"] },
	discount: { name: "Discount", sizes: ["m", "l"] },
	"discount--filled": { name: "DiscountFilled", sizes: ["m", "l"] },
	"discount-increase": { name: "DiscountIncrease", sizes: ["m"] },
	display: { name: "Display", sizes: ["s", "m", "l"] },
	"display--filled": { name: "DisplayFilled", sizes: ["s", "m", "l"] },
	"display-add": { name: "DisplayAdd", sizes: ["l"] },
	"display-add--filled": { name: "DisplayAddFilled", sizes: ["l"] },
	"display-project": { name: "DisplayProject", sizes: ["l"] },
	"display-project--filled": { name: "DisplayProjectFilled", sizes: ["l"] },
	"display-project-check": { name: "DisplayProjectCheck", sizes: ["l"] },
	"display-project-check--filled": { name: "DisplayProjectCheckFilled", sizes: ["l"] },
	"display-project-set": { name: "DisplayProjectSet", sizes: ["l"] },
	"display-project-set--filled": { name: "DisplayProjectSetFilled", sizes: ["l"] },
	download: { name: "Download", sizes: ["s", "m", "l"] },
	drag: { name: "Drag", sizes: ["m", "l"] },
	droplet: { name: "Droplet", sizes: ["l"] },
	"droplet--filled": { name: "DropletFilled", sizes: ["l"] },
	"dry-clean-no": { name: "DryCleanNo", sizes: ["m"] },
	ear: { name: "Ear", sizes: ["l"] },
	"ear--filled": { name: "EarFilled", sizes: ["l"] },
	edit: { name: "Edit", sizes: ["m", "l"] },
	"edit--filled": { name: "EditFilled", sizes: ["m", "l"] },
	effect: { name: "Effect", sizes: ["l"] },
	elements: { name: "Elements", sizes: ["l"] },
	"elements--filled": { name: "ElementsFilled", sizes: ["l"] },
	ethernet: { name: "Ethernet", sizes: ["m"] },
	"ethernet--filled": { name: "EthernetFilled", sizes: ["m"] },
	"exit-fullscreen": { name: "ExitFullscreen", sizes: ["m", "l"] },
	"expand-square": { name: "ExpandSquare", sizes: ["l"] },
	"expand-square--filled": { name: "ExpandSquareFilled", sizes: ["l"] },
	"external-link": { name: "ExternalLink", sizes: ["m", "l"] },
	"eye-contact": { name: "EyeContact", sizes: ["l"] },
	"eye-contact--filled": { name: "EyeContactFilled", sizes: ["l"] },
	"eye-contact-check": { name: "EyeContactCheck", sizes: ["l"] },
	"eye-contact-check--filled": { name: "EyeContactCheckFilled", sizes: ["l"] },
	eyedropper: { name: "Eyedropper", sizes: ["l"] },
	"eyedropper--filled": { name: "EyedropperFilled", sizes: ["l"] },
	"face-satisfied": { name: "FaceSatisfied", sizes: ["m", "l"] },
	"face-satisfied--filled": { name: "FaceSatisfiedFilled", sizes: ["m", "l"] },
	"face-satisfied-add": { name: "FaceSatisfiedAdd", sizes: ["l"] },
	"face-satisfied-add--filled": { name: "FaceSatisfiedAddFilled", sizes: ["l"] },
	"face-tracking": { name: "FaceTracking", sizes: ["l"] },
	"face-tracking-check": { name: "FaceTrackingCheck", sizes: ["l"] },
	facecam: { name: "Facecam", sizes: ["m", "l"] },
	"facecam--filled": { name: "FacecamFilled", sizes: ["m", "l"] },
	"facecam-neo": { name: "FacecamNeo", sizes: ["l"] },
	"facecam-neo--filled": { name: "FacecamNeoFilled", sizes: ["l"] },
	"facecam-off": { name: "FacecamOff", sizes: ["l"] },
	"facecam-off--filled": { name: "FacecamOffFilled", sizes: ["l"] },
	file: { name: "File", sizes: ["m", "l"] },
	"file--filled": { name: "FileFilled", sizes: ["m", "l"] },
	"file-download": { name: "FileDownload", sizes: ["l"] },
	"file-download--filled": { name: "FileDownloadFilled", sizes: ["l"] },
	"file-upload": { name: "FileUpload", sizes: ["l"] },
	"file-upload--filled": { name: "FileUploadFilled", sizes: ["l"] },
	film: { name: "Film", sizes: ["m", "l"] },
	"film--filled": { name: "FilmFilled", sizes: ["m", "l"] },
	filter: { name: "Filter", sizes: ["m", "l"] },
	"filter--filled": { name: "FilterFilled", sizes: ["m"] },
	"filter-alt": { name: "FilterAlt", sizes: ["l"] },
	"filter-alt--filled": { name: "FilterAltFilled", sizes: ["l"] },
	flame: { name: "Flame", sizes: ["l"] },
	"flame--filled": { name: "FlameFilled", sizes: ["l"] },
	flash: { name: "Flash", sizes: ["l"] },
	"flash--filled": { name: "FlashFilled", sizes: ["l"] },
	"flash-off": { name: "FlashOff", sizes: ["l"] },
	"flash-off--filled": { name: "FlashOffFilled", sizes: ["l"] },
	"flip-horizontal": { name: "FlipHorizontal", sizes: ["l"] },
	"flip-horizontal--filled": { name: "FlipHorizontalFilled", sizes: ["l"] },
	"flip-horizontal-check": { name: "FlipHorizontalCheck", sizes: ["l"] },
	"flip-horizontal-check--filled": { name: "FlipHorizontalCheckFilled", sizes: ["l"] },
	"flip-vertical": { name: "FlipVertical", sizes: ["l"] },
	"flip-vertical--filled": { name: "FlipVerticalFilled", sizes: ["l"] },
	"flip-vertical-check": { name: "FlipVerticalCheck", sizes: ["l"] },
	"flip-vertical-check--filled": { name: "FlipVerticalCheckFilled", sizes: ["l"] },
	flow: { name: "Flow", sizes: ["m"] },
	"flow--filled": { name: "FlowFilled", sizes: ["m"] },
	focus: { name: "Focus", sizes: ["l"] },
	"focus--filled": { name: "FocusFilled", sizes: ["l"] },
	folder: { name: "Folder", sizes: ["m", "l"] },
	"folder--filled": { name: "FolderFilled", sizes: ["m", "l"] },
	"folder-back": { name: "FolderBack", sizes: ["l"] },
	"folder-back--filled": { name: "FolderBackFilled", sizes: ["l"] },
	"folder-download": { name: "FolderDownload", sizes: ["l"] },
	"folder-download--filled": { name: "FolderDownloadFilled", sizes: ["l"] },
	"folder-open": { name: "FolderOpen", sizes: ["m", "l"] },
	"folder-open--filled": { name: "FolderOpenFilled", sizes: ["m", "l"] },
	"folder-upload": { name: "FolderUpload", sizes: ["l"] },
	"folder-upload--filled": { name: "FolderUploadFilled", sizes: ["l"] },
	forest: { name: "Forest", sizes: ["l"] },
	"forest--filled": { name: "ForestFilled", sizes: ["l"] },
	fullscreen: { name: "Fullscreen", sizes: ["m", "l"] },
	game: { name: "Game", sizes: ["s", "m", "l"] },
	"game--filled": { name: "GameFilled", sizes: ["s", "m", "l"] },
	"game-add": { name: "GameAdd", sizes: ["l"] },
	"game-add--filled": { name: "GameAddFilled", sizes: ["l"] },
	"gap-horizontal": { name: "GapHorizontal", sizes: ["l"] },
	"gap-horizontal--filled": { name: "GapHorizontalFilled", sizes: ["l"] },
	"gap-vertical": { name: "GapVertical", sizes: ["l"] },
	"gap-vertical--filled": { name: "GapVerticalFilled", sizes: ["l"] },
	gift: { name: "Gift", sizes: ["m"] },
	"gift--filled": { name: "GiftFilled", sizes: ["m"] },
	globe: { name: "Globe", sizes: ["m", "l"] },
	"globe--filled": { name: "GlobeFilled", sizes: ["m", "l"] },
	"globe-add": { name: "GlobeAdd", sizes: ["l"] },
	"globe-add--filled": { name: "GlobeAddFilled", sizes: ["l"] },
	"gradient-linear": { name: "GradientLinear", sizes: ["m"] },
	"gradient-linear--filled": { name: "GradientLinearFilled", sizes: ["m"] },
	grid: { name: "Grid", sizes: ["m", "l"] },
	"grid--filled": { name: "GridFilled", sizes: ["m", "l"] },
	group: { name: "Group", sizes: ["m", "l"] },
	"group--filled": { name: "GroupFilled", sizes: ["m", "l"] },
	"hand-point-up": { name: "HandPointUp", sizes: ["l"] },
	hdmi: { name: "Hdmi", sizes: ["s", "m", "l"] },
	"hdmi--filled": { name: "HdmiFilled", sizes: ["s", "m", "l"] },
	hdr: { name: "Hdr", sizes: ["l"] },
	headphones: { name: "Headphones", sizes: ["m", "l"] },
	"headphones--filled": { name: "HeadphonesFilled", sizes: ["m", "l"] },
	"headphones-add": { name: "HeadphonesAdd", sizes: ["l"] },
	"headphones-add--filled": { name: "HeadphonesAddFilled", sizes: ["l"] },
	"headphones-off": { name: "HeadphonesOff", sizes: ["l"] },
	"headphones-off--filled": { name: "HeadphonesOffFilled", sizes: ["l"] },
	"headphones-switch-to": { name: "HeadphonesSwitchTo", sizes: ["l"] },
	"headphones-switch-to--filled": { name: "HeadphonesSwitchToFilled", sizes: ["l"] },
	heart: { name: "Heart", sizes: ["l"] },
	"heart--filled": { name: "HeartFilled", sizes: ["l"] },
	"heat-sink": { name: "HeatSink", sizes: ["l"] },
	help: { name: "Help", sizes: ["m", "l"] },
	"help--filled": { name: "HelpFilled", sizes: ["m", "l"] },
	hexagon: { name: "Hexagon", sizes: ["l"] },
	"hexagon--filled": { name: "HexagonFilled", sizes: ["l"] },
	home: { name: "Home", sizes: ["m", "l"] },
	"home--filled": { name: "HomeFilled", sizes: ["m", "l"] },
	hotkey: { name: "Hotkey", sizes: ["m", "l"] },
	"hotkey--filled": { name: "HotkeyFilled", sizes: ["m", "l"] },
	image: { name: "Image", sizes: ["m", "l"] },
	"image--filled": { name: "ImageFilled", sizes: ["m", "l"] },
	"image-check": { name: "ImageCheck", sizes: ["l"] },
	"image-check--filled": { name: "ImageCheckFilled", sizes: ["l"] },
	inbox: { name: "Inbox", sizes: ["l"] },
	"inbox--filled": { name: "InboxFilled", sizes: ["l"] },
	info: { name: "Info", sizes: ["s", "m", "l"] },
	"info--filled": { name: "InfoFilled", sizes: ["s", "m", "l"] },
	infobar: { name: "Infobar", sizes: ["s", "m", "l"] },
	"infobar--filled": { name: "InfobarFilled", sizes: ["s", "m", "l"] },
	"iron-low": { name: "IronLow", sizes: ["m"] },
	italic: { name: "Italic", sizes: ["m", "l"] },
	key: { name: "Key", sizes: ["l"] },
	"key--filled": { name: "KeyFilled", sizes: ["l"] },
	"key-light": { name: "KeyLight", sizes: ["l"] },
	"key-light--filled": { name: "KeyLightFilled", sizes: ["l"] },
	"key-light-air": { name: "KeyLightAir", sizes: ["l"] },
	"key-light-air--filled": { name: "KeyLightAirFilled", sizes: ["l"] },
	"key-light-air-off": { name: "KeyLightAirOff", sizes: ["l"] },
	"key-light-air-off--filled": { name: "KeyLightAirOffFilled", sizes: ["l"] },
	"key-light-air-power": { name: "KeyLightAirPower", sizes: ["l"] },
	"key-light-air-power--filled": { name: "KeyLightAirPowerFilled", sizes: ["l"] },
	"key-light-mini": { name: "KeyLightMini", sizes: ["l"] },
	"key-light-mini--filled": { name: "KeyLightMiniFilled", sizes: ["l"] },
	"key-light-mini-off": { name: "KeyLightMiniOff", sizes: ["l"] },
	"key-light-mini-off--filled": { name: "KeyLightMiniOffFilled", sizes: ["l"] },
	"key-light-mini-power": { name: "KeyLightMiniPower", sizes: ["l"] },
	"key-light-mini-power--filled": { name: "KeyLightMiniPowerFilled", sizes: ["l"] },
	"key-light-neo": { name: "KeyLightNeo", sizes: ["l"] },
	"key-light-neo--filled": { name: "KeyLightNeoFilled", sizes: ["l"] },
	"key-light-neo-off": { name: "KeyLightNeoOff", sizes: ["l"] },
	"key-light-neo-off--filled": { name: "KeyLightNeoOffFilled", sizes: ["l"] },
	"key-light-neo-power": { name: "KeyLightNeoPower", sizes: ["l"] },
	"key-light-neo-power--filled": { name: "KeyLightNeoPowerFilled", sizes: ["l"] },
	"key-light-off": { name: "KeyLightOff", sizes: ["l"] },
	"key-light-off--filled": { name: "KeyLightOffFilled", sizes: ["l"] },
	"key-light-power": { name: "KeyLightPower", sizes: ["l"] },
	"key-light-power--filled": { name: "KeyLightPowerFilled", sizes: ["l"] },
	keyboard: { name: "Keyboard", sizes: ["l"] },
	"keyboard--filled": { name: "KeyboardFilled", sizes: ["l"] },
	"keyboard-emoji": { name: "KeyboardEmoji", sizes: ["l"] },
	"keyboard-emoji--filled": { name: "KeyboardEmojiFilled", sizes: ["l"] },
	laptop: { name: "Laptop", sizes: ["l"] },
	"laptop--filled": { name: "LaptopFilled", sizes: ["l"] },
	layers: { name: "Layers", sizes: ["l"] },
	"layers--filled": { name: "LayersFilled", sizes: ["l"] },
	learn: { name: "Learn", sizes: ["m", "l"] },
	"learn--filled": { name: "LearnFilled", sizes: ["m", "l"] },
	lens: { name: "Lens", sizes: ["l"] },
	"lens--filled": { name: "LensFilled", sizes: ["l"] },
	"lens-check": { name: "LensCheck", sizes: ["l"] },
	"lens-check--filled": { name: "LensCheckFilled", sizes: ["l"] },
	library: { name: "Library", sizes: ["l"] },
	"library--filled": { name: "LibraryFilled", sizes: ["l"] },
	"light-bulb": { name: "LightBulb", sizes: ["m"] },
	"light-bulb--filled": { name: "LightBulbFilled", sizes: ["m"] },
	"light-strip": { name: "LightStrip", sizes: ["l"] },
	"light-strip--filled": { name: "LightStripFilled", sizes: ["l"] },
	"light-strip-off": { name: "LightStripOff", sizes: ["l"] },
	"light-strip-off--filled": { name: "LightStripOffFilled", sizes: ["l"] },
	"light-strip-power": { name: "LightStripPower", sizes: ["l"] },
	"light-strip-power--filled": { name: "LightStripPowerFilled", sizes: ["l"] },
	link: { name: "Link", sizes: ["m", "l"] },
	"link-broken": { name: "LinkBroken", sizes: ["m", "l"] },
	list: { name: "List", sizes: ["m", "l"] },
	location: { name: "Location", sizes: ["l"] },
	"location--filled": { name: "LocationFilled", sizes: ["l"] },
	lock: { name: "Lock", sizes: ["m", "l"] },
	"lock--filled": { name: "LockFilled", sizes: ["m", "l"] },
	"lock-open": { name: "LockOpen", sizes: ["l"] },
	"lock-open--filled": { name: "LockOpenFilled", sizes: ["l"] },
	"logo-adobe": { name: "LogoAdobe", sizes: ["l"] },
	"logo-adobe--color": { name: "LogoAdobeColor", sizes: ["l"] },
	"logo-adobe-acrobat": { name: "LogoAdobeAcrobat", sizes: ["l"] },
	"logo-adobe-acrobat--color": { name: "LogoAdobeAcrobatColor", sizes: ["l"] },
	"logo-adobe-audition": { name: "LogoAdobeAudition", sizes: ["l"] },
	"logo-adobe-audition--color": { name: "LogoAdobeAuditionColor", sizes: ["l"] },
	"logo-adobe-character-animator": { name: "LogoAdobeCharacterAnimator", sizes: ["l"] },
	"logo-adobe-character-animator--color": { name: "LogoAdobeCharacterAnimatorColor", sizes: ["l"] },
	"logo-adobe-creative-cloud": { name: "LogoAdobeCreativeCloud", sizes: ["l"] },
	"logo-adobe-creative-cloud--color": { name: "LogoAdobeCreativeCloudColor", sizes: ["l"] },
	"logo-adobe-express": { name: "LogoAdobeExpress", sizes: ["l"] },
	"logo-adobe-express--color": { name: "LogoAdobeExpressColor", sizes: ["l"] },
	"logo-adobe-illustrator": { name: "LogoAdobeIllustrator", sizes: ["l"] },
	"logo-adobe-illustrator--color": { name: "LogoAdobeIllustratorColor", sizes: ["l"] },
	"logo-adobe-indesign": { name: "LogoAdobeIndesign", sizes: ["l"] },
	"logo-adobe-indesign--color": { name: "LogoAdobeIndesignColor", sizes: ["l"] },
	"logo-adobe-lightroom": { name: "LogoAdobeLightroom", sizes: ["l"] },
	"logo-adobe-lightroom--color": { name: "LogoAdobeLightroomColor", sizes: ["l"] },
	"logo-adobe-media-encoder": { name: "LogoAdobeMediaEncoder", sizes: ["l"] },
	"logo-adobe-media-encoder--color": { name: "LogoAdobeMediaEncoderColor", sizes: ["l"] },
	"logo-adobe-photoshop": { name: "LogoAdobePhotoshop", sizes: ["l"] },
	"logo-adobe-photoshop--color": { name: "LogoAdobePhotoshopColor", sizes: ["l"] },
	"logo-adobe-premiere-pro": { name: "LogoAdobePremierePro", sizes: ["l"] },
	"logo-adobe-premiere-pro--color": { name: "LogoAdobePremiereProColor", sizes: ["l"] },
	"logo-after-effects": { name: "LogoAfterEffects", sizes: ["l"] },
	"logo-after-effects--color": { name: "LogoAfterEffectsColor", sizes: ["l"] },
	"logo-airtable": { name: "LogoAirtable", sizes: ["l"] },
	"logo-airtable--color": { name: "LogoAirtableColor", sizes: ["l"] },
	"logo-amazon": { name: "LogoAmazon", sizes: ["l"] },
	"logo-amazon--color": { name: "LogoAmazonColor", sizes: ["l"] },
	"logo-amazon-alexa": { name: "LogoAmazonAlexa", sizes: ["l"] },
	"logo-amazon-alexa--color": { name: "LogoAmazonAlexaColor", sizes: ["l"] },
	"logo-android": { name: "LogoAndroid", sizes: ["l"] },
	"logo-android--color": { name: "LogoAndroidColor", sizes: ["l"] },
	"logo-anthropic": { name: "LogoAnthropic", sizes: ["l"] },
	"logo-apple": { name: "LogoApple", sizes: ["l"] },
	"logo-apple-home": { name: "LogoAppleHome", sizes: ["l"] },
	"logo-apple-intelligence": { name: "LogoAppleIntelligence", sizes: ["l"] },
	"logo-apple-intelligence--color": { name: "LogoAppleIntelligenceColor", sizes: ["l"] },
	"logo-apple-music": { name: "LogoAppleMusic", sizes: ["l"] },
	"logo-apple-music--color": { name: "LogoAppleMusicColor", sizes: ["l"] },
	"logo-asana": { name: "LogoAsana", sizes: ["l"] },
	"logo-asana--color": { name: "LogoAsanaColor", sizes: ["l"] },
	"logo-atlassian-confluence": { name: "LogoAtlassianConfluence", sizes: ["l"] },
	"logo-atlassian-confluence--color": { name: "LogoAtlassianConfluenceColor", sizes: ["l"] },
	"logo-atlassian-jira": { name: "LogoAtlassianJira", sizes: ["l"] },
	"logo-atlassian-jira--color": { name: "LogoAtlassianJiraColor", sizes: ["l"] },
	"logo-audio-technica": { name: "LogoAudioTechnica", sizes: ["l"] },
	"logo-behance": { name: "LogoBehance", sizes: ["l"] },
	"logo-best-buy": { name: "LogoBestBuy", sizes: ["l"] },
	"logo-best-buy--color": { name: "LogoBestBuyColor", sizes: ["l"] },
	"logo-bitcoin": { name: "LogoBitcoin", sizes: ["l"] },
	"logo-bitcoin--color": { name: "LogoBitcoinColor", sizes: ["l"] },
	"logo-blender": { name: "LogoBlender", sizes: ["l"] },
	"logo-blender--color": { name: "LogoBlenderColor", sizes: ["l"] },
	"logo-brave": { name: "LogoBrave", sizes: ["l"] },
	"logo-brave--color": { name: "LogoBraveColor", sizes: ["l"] },
	"logo-calendly": { name: "LogoCalendly", sizes: ["l"] },
	"logo-calendly--color": { name: "LogoCalendlyColor", sizes: ["l"] },
	"logo-camera-hub": { name: "LogoCameraHub", sizes: ["s", "m"] },
	"logo-camera-hub--color": { name: "LogoCameraHubColor", sizes: ["s", "m"] },
	"logo-camera-hub--filled": { name: "LogoCameraHubFilled", sizes: ["s", "m"] },
	"logo-capture": { name: "LogoCapture", sizes: ["s", "m"] },
	"logo-capture--color": { name: "LogoCaptureColor", sizes: ["s", "m"] },
	"logo-capture--filled": { name: "LogoCaptureFilled", sizes: ["s", "m"] },
	"logo-chrome": { name: "LogoChrome", sizes: ["l"] },
	"logo-chrome--color": { name: "LogoChromeColor", sizes: ["l"] },
	"logo-claude": { name: "LogoClaude", sizes: ["l"] },
	"logo-claude--color": { name: "LogoClaudeColor", sizes: ["l"] },
	"logo-control-center": { name: "LogoControlCenter", sizes: ["s", "m"] },
	"logo-control-center--color": { name: "LogoControlCenterColor", sizes: ["s", "m"] },
	"logo-control-center--filled": { name: "LogoControlCenterFilled", sizes: ["s", "m"] },
	"logo-corsair": { name: "LogoCorsair", sizes: ["l"] },
	"logo-css": { name: "LogoCss", sizes: ["m"] },
	"logo-css--color": { name: "LogoCssColor", sizes: ["l"] },
	"logo-cursor": { name: "LogoCursor", sizes: ["l"] },
	"logo-deepseek": { name: "LogoDeepseek", sizes: ["l"] },
	"logo-deepseek--color": { name: "LogoDeepseekColor", sizes: ["l"] },
	"logo-discord": { name: "LogoDiscord", sizes: ["l"] },
	"logo-discord--color": { name: "LogoDiscordColor", sizes: ["l"] },
	"logo-dribbble": { name: "LogoDribbble", sizes: ["l"] },
	"logo-dribbble--color": { name: "LogoDribbbleColor", sizes: ["l"] },
	"logo-dropbox": { name: "LogoDropbox", sizes: ["l"] },
	"logo-dropbox--color": { name: "LogoDropboxColor", sizes: ["l"] },
	"logo-eclipse": { name: "LogoEclipse", sizes: ["l"] },
	"logo-eclipse--color": { name: "LogoEclipseColor", sizes: ["l"] },
	"logo-elgato": { name: "LogoElgato", sizes: ["l"] },
	"logo-epic-games": { name: "LogoEpicGames", sizes: ["l"] },
	"logo-ethereum": { name: "LogoEthereum", sizes: ["l"] },
	"logo-ethereum--color": { name: "LogoEthereumColor", sizes: ["l"] },
	"logo-explorer": { name: "LogoExplorer", sizes: ["m", "l"] },
	"logo-facebook": { name: "LogoFacebook", sizes: ["l"] },
	"logo-facebook--color": { name: "LogoFacebookColor", sizes: ["l"] },
	"logo-figma": { name: "LogoFigma", sizes: ["l"] },
	"logo-figma--color": { name: "LogoFigmaColor", sizes: ["l"] },
	"logo-firefox-browser": { name: "LogoFirefoxBrowser", sizes: ["l"] },
	"logo-firefox-browser--color": { name: "LogoFirefoxBrowserColor", sizes: ["l"] },
	"logo-frameio": { name: "LogoFrameio", sizes: ["l"] },
	"logo-frameio--color": { name: "LogoFrameioColor", sizes: ["l"] },
	"logo-framer": { name: "LogoFramer", sizes: ["l"] },
	"logo-gamer-sensei": { name: "LogoGamerSensei", sizes: ["l"] },
	"logo-gamer-sensei--color": { name: "LogoGamerSenseiColor", sizes: ["l"] },
	"logo-github": { name: "LogoGithub", sizes: ["l"] },
	"logo-github-copilot": { name: "LogoGithubCopilot", sizes: ["l"] },
	"logo-gitlab": { name: "LogoGitlab", sizes: ["l"] },
	"logo-gitlab--color": { name: "LogoGitlabColor", sizes: ["l"] },
	"logo-gmail": { name: "LogoGmail", sizes: ["l"] },
	"logo-gmail--color": { name: "LogoGmailColor", sizes: ["l"] },
	"logo-google": { name: "LogoGoogle", sizes: ["l"] },
	"logo-google--color": { name: "LogoGoogleColor", sizes: ["l"] },
	"logo-google-assistant": { name: "LogoGoogleAssistant", sizes: ["l"] },
	"logo-google-assistant--color": { name: "LogoGoogleAssistantColor", sizes: ["l"] },
	"logo-google-calendar": { name: "LogoGoogleCalendar", sizes: ["l"] },
	"logo-google-calendar--color": { name: "LogoGoogleCalendarColor", sizes: ["l"] },
	"logo-google-chat": { name: "LogoGoogleChat", sizes: ["l"] },
	"logo-google-chat--color": { name: "LogoGoogleChatColor", sizes: ["l"] },
	"logo-google-docs": { name: "LogoGoogleDocs", sizes: ["l"] },
	"logo-google-docs--color": { name: "LogoGoogleDocsColor", sizes: ["l"] },
	"logo-google-drive": { name: "LogoGoogleDrive", sizes: ["l"] },
	"logo-google-drive--color": { name: "LogoGoogleDriveColor", sizes: ["l"] },
	"logo-google-forms": { name: "LogoGoogleForms", sizes: ["l"] },
	"logo-google-forms--color": { name: "LogoGoogleFormsColor", sizes: ["l"] },
	"logo-google-gemini": { name: "LogoGoogleGemini", sizes: ["l"] },
	"logo-google-gemini--color": { name: "LogoGoogleGeminiColor", sizes: ["l"] },
	"logo-google-maps": { name: "LogoGoogleMaps", sizes: ["l"] },
	"logo-google-maps--color": { name: "LogoGoogleMapsColor", sizes: ["l"] },
	"logo-google-meet": { name: "LogoGoogleMeet", sizes: ["l"] },
	"logo-google-meet--color": { name: "LogoGoogleMeetColor", sizes: ["l"] },
	"logo-google-photos": { name: "LogoGooglePhotos", sizes: ["l"] },
	"logo-google-photos--color": { name: "LogoGooglePhotosColor", sizes: ["l"] },
	"logo-google-sheets": { name: "LogoGoogleSheets", sizes: ["l"] },
	"logo-google-sheets--color": { name: "LogoGoogleSheetsColor", sizes: ["l"] },
	"logo-google-sites": { name: "LogoGoogleSites", sizes: ["l"] },
	"logo-google-sites--color": { name: "LogoGoogleSitesColor", sizes: ["l"] },
	"logo-google-slides": { name: "LogoGoogleSlides", sizes: ["l"] },
	"logo-google-slides--color": { name: "LogoGoogleSlidesColor", sizes: ["l"] },
	"logo-google-translate": { name: "LogoGoogleTranslate", sizes: ["l"] },
	"logo-google-translate--color": { name: "LogoGoogleTranslateColor", sizes: ["l"] },
	"logo-grok": { name: "LogoGrok", sizes: ["l"] },
	"logo-html": { name: "LogoHtml", sizes: ["m"] },
	"logo-html--color": { name: "LogoHtmlColor", sizes: ["m"] },
	"logo-instagram": { name: "LogoInstagram", sizes: ["l"] },
	"logo-instagram--color": { name: "LogoInstagramColor", sizes: ["l"] },
	"logo-intel": { name: "LogoIntel", sizes: ["l"] },
	"logo-intel--color": { name: "LogoIntelColor", sizes: ["l"] },
	"logo-js": { name: "LogoJs", sizes: ["m"] },
	"logo-js--color": { name: "LogoJsColor", sizes: ["m"] },
	"logo-kick": { name: "LogoKick", sizes: ["l"] },
	"logo-kick--color": { name: "LogoKickColor", sizes: ["l"] },
	"logo-linear": { name: "LogoLinear", sizes: ["l"] },
	"logo-linear--color": { name: "LogoLinearColor", sizes: ["l"] },
	"logo-linkedin": { name: "LogoLinkedin", sizes: ["l"] },
	"logo-linkedin--color": { name: "LogoLinkedinColor", sizes: ["l"] },
	"logo-lovable": { name: "LogoLovable", sizes: ["l"] },
	"logo-lovable--color": { name: "LogoLovableColor", sizes: ["l"] },
	"logo-lua": { name: "LogoLua", sizes: ["m"] },
	"logo-lua--color": { name: "LogoLuaColor", sizes: ["m"] },
	"logo-macos": { name: "LogoMacos", sizes: ["l"] },
	"logo-markdown": { name: "LogoMarkdown", sizes: ["l"] },
	"logo-marketplace": { name: "LogoMarketplace", sizes: ["l"] },
	"logo-marketplace--color": { name: "LogoMarketplaceColor", sizes: ["l"] },
	"logo-matter": { name: "LogoMatter", sizes: ["l"] },
	"logo-medium": { name: "LogoMedium", sizes: ["l"] },
	"logo-meld-studio": { name: "LogoMeldStudio", sizes: ["l"] },
	"logo-meta": { name: "LogoMeta", sizes: ["l"] },
	"logo-meta--color": { name: "LogoMetaColor", sizes: ["l"] },
	"logo-microsoft": { name: "LogoMicrosoft", sizes: ["l"] },
	"logo-microsoft--color": { name: "LogoMicrosoftColor", sizes: ["l"] },
	"logo-microsoft-copilot": { name: "LogoMicrosoftCopilot", sizes: ["l"] },
	"logo-microsoft-copilot--color": { name: "LogoMicrosoftCopilotColor", sizes: ["l"] },
	"logo-microsoft-excel": { name: "LogoMicrosoftExcel", sizes: ["l"] },
	"logo-microsoft-excel--color": { name: "LogoMicrosoftExcelColor", sizes: ["l"] },
	"logo-microsoft-forms": { name: "LogoMicrosoftForms", sizes: ["l"] },
	"logo-microsoft-forms--color": { name: "LogoMicrosoftFormsColor", sizes: ["l"] },
	"logo-microsoft-onedrive": { name: "LogoMicrosoftOnedrive", sizes: ["l"] },
	"logo-microsoft-onedrive--color": { name: "LogoMicrosoftOnedriveColor", sizes: ["l"] },
	"logo-microsoft-onenote": { name: "LogoMicrosoftOnenote", sizes: ["l"] },
	"logo-microsoft-onenote--color": { name: "LogoMicrosoftOnenoteColor", sizes: ["l"] },
	"logo-microsoft-outlook": { name: "LogoMicrosoftOutlook", sizes: ["l"] },
	"logo-microsoft-outlook--color": { name: "LogoMicrosoftOutlookColor", sizes: ["l"] },
	"logo-microsoft-powerpoint": { name: "LogoMicrosoftPowerpoint", sizes: ["l"] },
	"logo-microsoft-powerpoint--color": { name: "LogoMicrosoftPowerpointColor", sizes: ["l"] },
	"logo-microsoft-project": { name: "LogoMicrosoftProject", sizes: ["l"] },
	"logo-microsoft-project--color": { name: "LogoMicrosoftProjectColor", sizes: ["l"] },
	"logo-microsoft-sharepoint": { name: "LogoMicrosoftSharepoint", sizes: ["l"] },
	"logo-microsoft-sharepoint--color": { name: "LogoMicrosoftSharepointColor", sizes: ["l"] },
	"logo-microsoft-teams": { name: "LogoMicrosoftTeams", sizes: ["l"] },
	"logo-microsoft-teams--color": { name: "LogoMicrosoftTeamsColor", sizes: ["l"] },
	"logo-microsoft-todo": { name: "LogoMicrosoftTodo", sizes: ["l"] },
	"logo-microsoft-todo--color": { name: "LogoMicrosoftTodoColor", sizes: ["l"] },
	"logo-microsoft-visio": { name: "LogoMicrosoftVisio", sizes: ["l"] },
	"logo-microsoft-visio--color": { name: "LogoMicrosoftVisioColor", sizes: ["l"] },
	"logo-microsoft-word": { name: "LogoMicrosoftWord", sizes: ["l"] },
	"logo-microsoft-word--color": { name: "LogoMicrosoftWordColor", sizes: ["l"] },
	"logo-miro": { name: "LogoMiro", sizes: ["l"] },
	"logo-miro--color": { name: "LogoMiroColor", sizes: ["l"] },
	"logo-ndi": { name: "LogoNdi", sizes: ["l"] },
	"logo-nintendo-switch": { name: "LogoNintendoSwitch", sizes: ["l"] },
	"logo-nintendo-switch--color": { name: "LogoNintendoSwitchColor", sizes: ["l"] },
	"logo-notion": { name: "LogoNotion", sizes: ["l"] },
	"logo-notion--color": { name: "LogoNotionColor", sizes: ["l"] },
	"logo-nvidia": { name: "LogoNvidia", sizes: ["l"] },
	"logo-nvidia--color": { name: "LogoNvidiaColor", sizes: ["l"] },
	"logo-obs": { name: "LogoObs", sizes: ["m", "l"] },
	"logo-obs--color": { name: "LogoObsColor", sizes: ["m", "l"] },
	"logo-obs--filled": { name: "LogoObsFilled", sizes: ["m", "l"] },
	"logo-obsidian": { name: "LogoObsidian", sizes: ["l"] },
	"logo-obsidian--color": { name: "LogoObsidianColor", sizes: ["l"] },
	"logo-openai": { name: "LogoOpenai", sizes: ["l"] },
	"logo-origin": { name: "LogoOrigin", sizes: ["l"] },
	"logo-origin--color": { name: "LogoOriginColor", sizes: ["l"] },
	"logo-perplexity": { name: "LogoPerplexity", sizes: ["l"] },
	"logo-perplexity--color": { name: "LogoPerplexityColor", sizes: ["l"] },
	"logo-pinterest": { name: "LogoPinterest", sizes: ["l"] },
	"logo-pinterest--color": { name: "LogoPinterestColor", sizes: ["l"] },
	"logo-play-station": { name: "LogoPlayStation", sizes: ["l"] },
	"logo-play-station--color": { name: "LogoPlayStationColor", sizes: ["l"] },
	"logo-python": { name: "LogoPython", sizes: ["l"] },
	"logo-python--color": { name: "LogoPythonColor", sizes: ["l"] },
	"logo-qt": { name: "LogoQt", sizes: ["l"] },
	"logo-qt--color": { name: "LogoQtColor", sizes: ["l"] },
	"logo-raycast": { name: "LogoRaycast", sizes: ["l"] },
	"logo-raycast--color": { name: "LogoRaycastColor", sizes: ["l"] },
	"logo-react": { name: "LogoReact", sizes: ["l"] },
	"logo-react--color": { name: "LogoReactColor", sizes: ["l"] },
	"logo-reddit": { name: "LogoReddit", sizes: ["l"] },
	"logo-reddit--color": { name: "LogoRedditColor", sizes: ["l"] },
	"logo-scuf": { name: "LogoScuf", sizes: ["l"] },
	"logo-scuf--color": { name: "LogoScufColor", sizes: ["l"] },
	"logo-shopify": { name: "LogoShopify", sizes: ["l"] },
	"logo-shopify--color": { name: "LogoShopifyColor", sizes: ["l"] },
	"logo-siri": { name: "LogoSiri", sizes: ["l"] },
	"logo-sketch": { name: "LogoSketch", sizes: ["l"] },
	"logo-sketch--color": { name: "LogoSketchColor", sizes: ["l"] },
	"logo-skype": { name: "LogoSkype", sizes: ["l"] },
	"logo-skype--color": { name: "LogoSkypeColor", sizes: ["l"] },
	"logo-slack": { name: "LogoSlack", sizes: ["l"] },
	"logo-slack--color": { name: "LogoSlackColor", sizes: ["l"] },
	"logo-snapchat": { name: "LogoSnapchat", sizes: ["l"] },
	"logo-snapchat--color": { name: "LogoSnapchatColor", sizes: ["l"] },
	"logo-snapchat-check": { name: "LogoSnapchatCheck", sizes: ["l"] },
	"logo-snapchat-reset": { name: "LogoSnapchatReset", sizes: ["l"] },
	"logo-snapchat-set": { name: "LogoSnapchatSet", sizes: ["l"] },
	"logo-spotify": { name: "LogoSpotify", sizes: ["l"] },
	"logo-spotify--color": { name: "LogoSpotifyColor", sizes: ["l"] },
	"logo-steam": { name: "LogoSteam", sizes: ["l"] },
	"logo-steam--color": { name: "LogoSteamColor", sizes: ["l"] },
	"logo-steam-deck": { name: "LogoSteamDeck", sizes: ["l"] },
	"logo-steam-deck--color": { name: "LogoSteamDeckColor", sizes: ["l"] },
	"logo-stream-deck": { name: "LogoStreamDeck", sizes: ["s", "m"] },
	"logo-stream-deck--color": { name: "LogoStreamDeckColor", sizes: ["s", "m"] },
	"logo-streamelements": { name: "LogoStreamelements", sizes: ["m"] },
	"logo-streamelements--color": { name: "LogoStreamelementsColor", sizes: ["m"] },
	"logo-streamlabs": { name: "LogoStreamlabs", sizes: ["m"] },
	"logo-streamlabs--color": { name: "LogoStreamlabsColor", sizes: ["m"] },
	"logo-stripe": { name: "LogoStripe", sizes: ["l"] },
	"logo-stripe--color": { name: "LogoStripeColor", sizes: ["l"] },
	"logo-studio": { name: "LogoStudio", sizes: ["s", "m"] },
	"logo-studio--color": { name: "LogoStudioColor", sizes: ["s", "m"] },
	"logo-telegram": { name: "LogoTelegram", sizes: ["l"] },
	"logo-telegram--color": { name: "LogoTelegramColor", sizes: ["l"] },
	"logo-threads": { name: "LogoThreads", sizes: ["l"] },
	"logo-tiktok": { name: "LogoTiktok", sizes: ["l"] },
	"logo-tiktok--color": { name: "LogoTiktokColor", sizes: ["l"] },
	"logo-tumblr": { name: "LogoTumblr", sizes: ["l"] },
	"logo-twitch": { name: "LogoTwitch", sizes: ["l"] },
	"logo-twitch--color": { name: "LogoTwitchColor", sizes: ["l"] },
	"logo-twitter": { name: "LogoTwitter", sizes: ["l"] },
	"logo-twitter--color": { name: "LogoTwitterColor", sizes: ["l"] },
	"logo-v0": { name: "LogoV0", sizes: ["l"] },
	"logo-vercel": { name: "LogoVercel", sizes: ["l"] },
	"logo-visual-studio": { name: "LogoVisualStudio", sizes: ["l"] },
	"logo-visual-studio--color": { name: "LogoVisualStudioColor", sizes: ["l"] },
	"logo-visual-studio-code": { name: "LogoVisualStudioCode", sizes: ["l"] },
	"logo-visual-studio-code--color": { name: "LogoVisualStudioCodeColor", sizes: ["l"] },
	"logo-voicemod": { name: "LogoVoicemod", sizes: ["l"] },
	"logo-voicemod--color": { name: "LogoVoicemodColor", sizes: ["l"] },
	"logo-vue": { name: "LogoVue", sizes: ["l"] },
	"logo-vue--color": { name: "LogoVueColor", sizes: ["l"] },
	"logo-wave-cast": { name: "LogoWaveCast", sizes: ["s", "m"] },
	"logo-wave-cast--color": { name: "LogoWaveCastColor", sizes: ["s", "m"] },
	"logo-wave-link": { name: "LogoWaveLink", sizes: ["s", "m"] },
	"logo-wave-link--color": { name: "LogoWaveLinkColor", sizes: ["s", "m"] },
	"logo-webflow": { name: "LogoWebflow", sizes: ["l"] },
	"logo-webflow--color": { name: "LogoWebflowColor", sizes: ["l"] },
	"logo-webstorm": { name: "LogoWebstorm", sizes: ["l"] },
	"logo-webstorm--color": { name: "LogoWebstormColor", sizes: ["l"] },
	"logo-wechat": { name: "LogoWechat", sizes: ["l"] },
	"logo-windows": { name: "LogoWindows", sizes: ["l"] },
	"logo-windows--color": { name: "LogoWindowsColor", sizes: ["l"] },
	"logo-windsurf": { name: "LogoWindsurf", sizes: ["l"] },
	"logo-windsurf--color": { name: "LogoWindsurfColor", sizes: ["l"] },
	"logo-x": { name: "LogoX", sizes: ["l"] },
	"logo-xbox": { name: "LogoXbox", sizes: ["l"] },
	"logo-xbox--color": { name: "LogoXboxColor", sizes: ["l"] },
	"logo-youtube": { name: "LogoYoutube", sizes: ["l"] },
	"logo-youtube--color": { name: "LogoYoutubeColor", sizes: ["l"] },
	"logo-zapier": { name: "LogoZapier", sizes: ["l"] },
	"logo-zoom": { name: "LogoZoom", sizes: ["l"] },
	"logo-zoom--color": { name: "LogoZoomColor", sizes: ["l"] },
	logo4kcu: { name: "Logo4kcu", sizes: ["s", "l"] },
	"logo4kcu--filled": { name: "Logo4kcuFilled", sizes: ["s", "l"] },
	lut: { name: "Lut", sizes: ["s", "m", "l"] },
	"lut--filled": { name: "LutFilled", sizes: ["s", "m", "l"] },
	"machine-wash-cold-delicate": { name: "MachineWashColdDelicate", sizes: ["m"] },
	"magic-wand": { name: "MagicWand", sizes: ["l"] },
	"magic-wand--filled": { name: "MagicWandFilled", sizes: ["l"] },
	mail: { name: "Mail", sizes: ["m", "l"] },
	"mail--filled": { name: "MailFilled", sizes: ["m", "l"] },
	margin: { name: "Margin", sizes: ["l"] },
	"margin-decrease": { name: "MarginDecrease", sizes: ["l"] },
	"margin-increase": { name: "MarginIncrease", sizes: ["l"] },
	"margin-set": { name: "MarginSet", sizes: ["l"] },
	"margin-x": { name: "MarginX", sizes: ["l"] },
	"margin-x-decrease": { name: "MarginXDecrease", sizes: ["l"] },
	"margin-x-increase": { name: "MarginXIncrease", sizes: ["l"] },
	"margin-x-set": { name: "MarginXSet", sizes: ["l"] },
	"margin-y": { name: "MarginY", sizes: ["l"] },
	"margin-y-set": { name: "MarginYSet", sizes: ["l"] },
	"marketplace-brand": { name: "MarketplaceBrand", sizes: ["l"] },
	"marketplace-brand--filled": { name: "MarketplaceBrandFilled", sizes: ["l"] },
	"marketplace-create": { name: "MarketplaceCreate", sizes: ["l"] },
	"marketplace-create--filled": { name: "MarketplaceCreateFilled", sizes: ["l"] },
	"marketplace-engage": { name: "MarketplaceEngage", sizes: ["l"] },
	"marketplace-engage--filled": { name: "MarketplaceEngageFilled", sizes: ["l"] },
	"media-cast": { name: "MediaCast", sizes: ["m", "l"] },
	"media-cast--filled": { name: "MediaCastFilled", sizes: ["m", "l"] },
	menu: { name: "Menu", sizes: ["m", "l"] },
	message: { name: "Message", sizes: ["s", "m", "l"] },
	"message--filled": { name: "MessageFilled", sizes: ["s", "m", "l"] },
	"message-add": { name: "MessageAdd", sizes: ["l"] },
	"message-add--filled": { name: "MessageAddFilled", sizes: ["l"] },
	"message-check": { name: "MessageCheck", sizes: ["l"] },
	"message-check--filled": { name: "MessageCheckFilled", sizes: ["l"] },
	"message-down-to-bottom": { name: "MessageDownToBottom", sizes: ["l"] },
	"message-down-to-bottom--filled": { name: "MessageDownToBottomFilled", sizes: ["l"] },
	"message-set": { name: "MessageSet", sizes: ["l"] },
	"message-set--filled": { name: "MessageSetFilled", sizes: ["l"] },
	"message-up-to-top": { name: "MessageUpToTop", sizes: ["l"] },
	"message-up-to-top--filled": { name: "MessageUpToTopFilled", sizes: ["l"] },
	"metering-center-weighted": { name: "MeteringCenterWeighted", sizes: ["l"] },
	"metering-center-weighted--filled": { name: "MeteringCenterWeightedFilled", sizes: ["l"] },
	"metering-evaluative": { name: "MeteringEvaluative", sizes: ["l"] },
	"metering-spot": { name: "MeteringSpot", sizes: ["l"] },
	"metering-spot--filled": { name: "MeteringSpotFilled", sizes: ["l"] },
	microphone: { name: "Microphone", sizes: ["s", "m", "l"] },
	"microphone--filled": { name: "MicrophoneFilled", sizes: ["s", "m", "l"] },
	"microphone-off": { name: "MicrophoneOff", sizes: ["m", "l"] },
	"microphone-off--filled": { name: "MicrophoneOffFilled", sizes: ["m", "l"] },
	mobile: { name: "Mobile", sizes: ["m", "l"] },
	"mobile--filled": { name: "MobileFilled", sizes: ["m", "l"] },
	money: { name: "Money", sizes: ["l"] },
	"money--filled": { name: "MoneyFilled", sizes: ["l"] },
	more: { name: "More", sizes: ["m", "l"] },
	"more-alt": { name: "MoreAlt", sizes: ["m", "l"] },
	mountain: { name: "Mountain", sizes: ["l"] },
	"mountain--filled": { name: "MountainFilled", sizes: ["l"] },
	mouse: { name: "Mouse", sizes: ["l"] },
	"mouse--filled": { name: "MouseFilled", sizes: ["l"] },
	move: { name: "Move", sizes: ["l"] },
	"move-to-bottom": { name: "MoveToBottom", sizes: ["l"] },
	"move-to-center": { name: "MoveToCenter", sizes: ["l"] },
	"move-to-top": { name: "MoveToTop", sizes: ["l"] },
	"multi-action": { name: "MultiAction", sizes: ["m", "l"] },
	"multi-action--filled": { name: "MultiActionFilled", sizes: ["m", "l"] },
	"multi-action-switch": { name: "MultiActionSwitch", sizes: ["m", "l"] },
	"multi-action-switch--filled": { name: "MultiActionSwitchFilled", sizes: ["m", "l"] },
	"multi-mount": { name: "MultiMount", sizes: ["m", "l"] },
	music: { name: "Music", sizes: ["s", "m", "l"] },
	"music--filled": { name: "MusicFilled", sizes: ["s", "m", "l"] },
	"music-add": { name: "MusicAdd", sizes: ["l"] },
	"music-add--filled": { name: "MusicAddFilled", sizes: ["l"] },
	network: { name: "Network", sizes: ["m"] },
	"network--filled": { name: "NetworkFilled", sizes: ["m"] },
	new: { name: "New", sizes: ["l"] },
	"new--filled": { name: "NewFilled", sizes: ["l"] },
	nfc: { name: "Nfc", sizes: ["l"] },
	"nfc--filled": { name: "NfcFilled", sizes: ["l"] },
	night: { name: "Night", sizes: ["m", "l"] },
	"night--filled": { name: "NightFilled", sizes: ["m", "l"] },
	"not-allowed": { name: "NotAllowed", sizes: ["l"] },
	notification: { name: "Notification", sizes: ["m", "l"] },
	"notification--filled": { name: "NotificationFilled", sizes: ["m", "l"] },
	"notification-off": { name: "NotificationOff", sizes: ["l"] },
	"notification-off--filled": { name: "NotificationOffFilled", sizes: ["l"] },
	number0: { name: "Number0", sizes: ["l"] },
	"number0-square": { name: "Number0Square", sizes: ["l"] },
	"number0-square--filled": { name: "Number0SquareFilled", sizes: ["l"] },
	number1: { name: "Number1", sizes: ["l"] },
	"number1-square": { name: "Number1Square", sizes: ["l"] },
	"number1-square--filled": { name: "Number1SquareFilled", sizes: ["l"] },
	number10: { name: "Number10", sizes: ["l"] },
	"number10-square": { name: "Number10Square", sizes: ["l"] },
	"number10-square--filled": { name: "Number10SquareFilled", sizes: ["l"] },
	number2: { name: "Number2", sizes: ["l"] },
	"number2-square": { name: "Number2Square", sizes: ["l"] },
	"number2-square--filled": { name: "Number2SquareFilled", sizes: ["l"] },
	number3: { name: "Number3", sizes: ["l"] },
	"number3-square": { name: "Number3Square", sizes: ["l"] },
	"number3-square--filled": { name: "Number3SquareFilled", sizes: ["l"] },
	number4: { name: "Number4", sizes: ["l"] },
	"number4-square": { name: "Number4Square", sizes: ["l"] },
	"number4-square--filled": { name: "Number4SquareFilled", sizes: ["l"] },
	number5: { name: "Number5", sizes: ["l"] },
	"number5-square": { name: "Number5Square", sizes: ["l"] },
	"number5-square--filled": { name: "Number5SquareFilled", sizes: ["l"] },
	number6: { name: "Number6", sizes: ["l"] },
	"number6-square": { name: "Number6Square", sizes: ["l"] },
	"number6-square--filled": { name: "Number6SquareFilled", sizes: ["l"] },
	number7: { name: "Number7", sizes: ["l"] },
	"number7-square": { name: "Number7Square", sizes: ["l"] },
	"number7-square--filled": { name: "Number7SquareFilled", sizes: ["l"] },
	number8: { name: "Number8", sizes: ["l"] },
	"number8-square": { name: "Number8Square", sizes: ["l"] },
	"number8-square--filled": { name: "Number8SquareFilled", sizes: ["l"] },
	number9: { name: "Number9", sizes: ["l"] },
	"number9-square": { name: "Number9Square", sizes: ["l"] },
	"number9-square--filled": { name: "Number9SquareFilled", sizes: ["l"] },
	"numbered-list": { name: "NumberedList", sizes: ["m", "l"] },
	numbers: { name: "Numbers", sizes: ["m"] },
	octagon: { name: "Octagon", sizes: ["l"] },
	"octagon--filled": { name: "OctagonFilled", sizes: ["l"] },
	opacity: { name: "Opacity", sizes: ["l"] },
	"opacity-increase": { name: "OpacityIncrease", sizes: ["l"] },
	"opacity-set": { name: "OpacitySet", sizes: ["l"] },
	package: { name: "Package", sizes: ["l"] },
	"package--filled": { name: "PackageFilled", sizes: ["l"] },
	padding: { name: "Padding", sizes: ["l"] },
	"padding--filled": { name: "PaddingFilled", sizes: ["l"] },
	"padding-bottom": { name: "PaddingBottom", sizes: ["l"] },
	"padding-bottom--filled": { name: "PaddingBottomFilled", sizes: ["l"] },
	"padding-left": { name: "PaddingLeft", sizes: ["l"] },
	"padding-left--filled": { name: "PaddingLeftFilled", sizes: ["l"] },
	"padding-right": { name: "PaddingRight", sizes: ["l"] },
	"padding-right--filled": { name: "PaddingRightFilled", sizes: ["l"] },
	"padding-top": { name: "PaddingTop", sizes: ["l"] },
	"padding-top--filled": { name: "PaddingTopFilled", sizes: ["l"] },
	"padding-x": { name: "PaddingX", sizes: ["l"] },
	"padding-x--filled": { name: "PaddingXFilled", sizes: ["l"] },
	"padding-y": { name: "PaddingY", sizes: ["l"] },
	"padding-y--filled": { name: "PaddingYFilled", sizes: ["l"] },
	palette: { name: "Palette", sizes: ["m", "l"] },
	"palette--filled": { name: "PaletteFilled", sizes: ["m", "l"] },
	"panel-left": { name: "PanelLeft", sizes: ["m", "l"] },
	"panel-left--filled": { name: "PanelLeftFilled", sizes: ["m", "l"] },
	"panel-right": { name: "PanelRight", sizes: ["m", "l"] },
	"panel-right--filled": { name: "PanelRightFilled", sizes: ["m", "l"] },
	paste: { name: "Paste", sizes: ["l"] },
	"paste--filled": { name: "PasteFilled", sizes: ["l"] },
	pause: { name: "Pause", sizes: ["m", "l"] },
	"pause--filled": { name: "PauseFilled", sizes: ["m", "l"] },
	payment: { name: "Payment", sizes: ["m", "l"] },
	"payment--filled": { name: "PaymentFilled", sizes: ["m", "l"] },
	"pen-tool": { name: "PenTool", sizes: ["l"] },
	"pen-tool--filled": { name: "PenToolFilled", sizes: ["l"] },
	pentagon: { name: "Pentagon", sizes: ["l"] },
	"pentagon--filled": { name: "PentagonFilled", sizes: ["l"] },
	person: { name: "Person", sizes: ["m", "l"] },
	"person--filled": { name: "PersonFilled", sizes: ["m", "l"] },
	phone: { name: "Phone", sizes: ["l"] },
	"phone--filled": { name: "PhoneFilled", sizes: ["l"] },
	"phone-voice": { name: "PhoneVoice", sizes: ["l"] },
	"phone-voice--filled": { name: "PhoneVoiceFilled", sizes: ["l"] },
	"photo-grid": { name: "PhotoGrid", sizes: ["l"] },
	"photo-grid--filled": { name: "PhotoGridFilled", sizes: ["l"] },
	pin: { name: "Pin", sizes: ["s", "m", "l"] },
	"pin--filled": { name: "PinFilled", sizes: ["s", "m", "l"] },
	play: { name: "Play", sizes: ["m", "l"] },
	"play--filled": { name: "PlayFilled", sizes: ["m", "l"] },
	"play-circle": { name: "PlayCircle", sizes: ["l"] },
	"play-circle--filled": { name: "PlayCircleFilled", sizes: ["l"] },
	"play-pause": { name: "PlayPause", sizes: ["l"] },
	"play-pause--filled": { name: "PlayPauseFilled", sizes: ["l"] },
	plugin: { name: "Plugin", sizes: ["m", "l"] },
	"plugin--filled": { name: "PluginFilled", sizes: ["m", "l"] },
	podcast: { name: "Podcast", sizes: ["l"] },
	"podcast--filled": { name: "PodcastFilled", sizes: ["l"] },
	power: { name: "Power", sizes: ["l"] },
	"power-off": { name: "PowerOff", sizes: ["l"] },
	presentation: { name: "Presentation", sizes: ["l"] },
	"presentation--filled": { name: "PresentationFilled", sizes: ["l"] },
	"presentation-play": { name: "PresentationPlay", sizes: ["l"] },
	"presentation-play--filled": { name: "PresentationPlayFilled", sizes: ["l"] },
	profile: { name: "Profile", sizes: ["m", "l"] },
	"profile--filled": { name: "ProfileFilled", sizes: ["m", "l"] },
	"profile-switch": { name: "ProfileSwitch", sizes: ["m", "l"] },
	"profile-switch--filled": { name: "ProfileSwitchFilled", sizes: ["m", "l"] },
	prompter: { name: "Prompter", sizes: ["l"] },
	"prompter--filled": { name: "PrompterFilled", sizes: ["l"] },
	"qr-code": { name: "QrCode", sizes: ["l"] },
	"qr-code-scan": { name: "QrCodeScan", sizes: ["l"] },
	"question-mark": { name: "QuestionMark", sizes: ["s", "l"] },
	quote: { name: "Quote", sizes: ["l"] },
	"quote--filled": { name: "QuoteFilled", sizes: ["l"] },
	receipt: { name: "Receipt", sizes: ["m", "l"] },
	"receipt--filled": { name: "ReceiptFilled", sizes: ["m", "l"] },
	record: { name: "Record", sizes: ["l"] },
	"record--filled": { name: "RecordFilled", sizes: ["l"] },
	redo: { name: "Redo", sizes: ["l"] },
	reflect: { name: "Reflect", sizes: ["l"] },
	refresh: { name: "Refresh", sizes: ["l"] },
	reset: { name: "Reset", sizes: ["m", "l"] },
	"ring-light": { name: "RingLight", sizes: ["l"] },
	"ring-light--filled": { name: "RingLightFilled", sizes: ["l"] },
	"ring-light-off": { name: "RingLightOff", sizes: ["l"] },
	"ring-light-off--filled": { name: "RingLightOffFilled", sizes: ["l"] },
	"ring-light-power": { name: "RingLightPower", sizes: ["l"] },
	"ring-light-power--filled": { name: "RingLightPowerFilled", sizes: ["l"] },
	rocket: { name: "Rocket", sizes: ["l"] },
	"rocket--filled": { name: "RocketFilled", sizes: ["l"] },
	rotate: { name: "Rotate", sizes: ["l"] },
	rotate180: { name: "Rotate180", sizes: ["l"] },
	rotate360: { name: "Rotate360", sizes: ["l"] },
	rss: { name: "Rss", sizes: ["l"] },
	"rss--filled": { name: "RssFilled", sizes: ["l"] },
	"scene-collection": { name: "SceneCollection", sizes: ["m", "l"] },
	"scene-collection--filled": { name: "SceneCollectionFilled", sizes: ["m", "l"] },
	"screen-rotation": { name: "ScreenRotation", sizes: ["l"] },
	"screen-rotation--filled": { name: "ScreenRotationFilled", sizes: ["l"] },
	screenshot: { name: "Screenshot", sizes: ["l"] },
	scroll: { name: "Scroll", sizes: ["l"] },
	search: { name: "Search", sizes: ["s", "m", "l"] },
	"search--filled": { name: "SearchFilled", sizes: ["s", "m", "l"] },
	security: { name: "Security", sizes: ["m", "l"] },
	"security--filled": { name: "SecurityFilled", sizes: ["m", "l"] },
	send: { name: "Send", sizes: ["m"] },
	"send--filled": { name: "SendFilled", sizes: ["m"] },
	server: { name: "Server", sizes: ["l"] },
	settings: { name: "Settings", sizes: ["m", "l"] },
	"settings--filled": { name: "SettingsFilled", sizes: ["m", "l"] },
	"settings-adjust": { name: "SettingsAdjust", sizes: ["l"] },
	"settings-adjust-focus": { name: "SettingsAdjustFocus", sizes: ["l"] },
	"settings-adjust-focus-check": { name: "SettingsAdjustFocusCheck", sizes: ["l"] },
	shapes: { name: "Shapes", sizes: ["m", "l"] },
	"shapes--filled": { name: "ShapesFilled", sizes: ["m", "l"] },
	share: { name: "Share", sizes: ["m", "l"] },
	"share-web": { name: "ShareWeb", sizes: ["l"] },
	"share-web--filled": { name: "ShareWebFilled", sizes: ["l"] },
	sheet: { name: "Sheet", sizes: ["l"] },
	"sheet--filled": { name: "SheetFilled", sizes: ["l"] },
	shield: { name: "Shield", sizes: ["l"] },
	"shield--filled": { name: "ShieldFilled", sizes: ["l"] },
	"shield-off": { name: "ShieldOff", sizes: ["l"] },
	"shield-off--filled": { name: "ShieldOffFilled", sizes: ["l"] },
	shuffle: { name: "Shuffle", sizes: ["l"] },
	shutter: { name: "Shutter", sizes: ["m", "l"] },
	"sign-in": { name: "SignIn", sizes: ["m", "l"] },
	"sign-out": { name: "SignOut", sizes: ["m", "l"] },
	signal: { name: "Signal", sizes: ["m", "l"] },
	"signal-off": { name: "SignalOff", sizes: ["m", "l"] },
	signal1: { name: "Signal1", sizes: ["m", "l"] },
	signal2: { name: "Signal2", sizes: ["m", "l"] },
	signal3: { name: "Signal3", sizes: ["m", "l"] },
	"skip-back": { name: "SkipBack", sizes: ["l"] },
	"skip-back--filled": { name: "SkipBackFilled", sizes: ["l"] },
	"skip-forward": { name: "SkipForward", sizes: ["l"] },
	"skip-forward--filled": { name: "SkipForwardFilled", sizes: ["l"] },
	snorkel: { name: "Snorkel", sizes: ["l"] },
	"snorkel--filled": { name: "SnorkelFilled", sizes: ["l"] },
	sort: { name: "Sort", sizes: ["s", "m", "l"] },
	"sound-effect": { name: "SoundEffect", sizes: ["s", "m", "l"] },
	"sound-effect-add": { name: "SoundEffectAdd", sizes: ["l"] },
	speaker: { name: "Speaker", sizes: ["m", "l"] },
	"speaker--filled": { name: "SpeakerFilled", sizes: ["m", "l"] },
	"speaker-switch-to": { name: "SpeakerSwitchTo", sizes: ["l"] },
	"speaker-switch-to--filled": { name: "SpeakerSwitchToFilled", sizes: ["l"] },
	speech: { name: "Speech", sizes: ["m", "l"] },
	"speech--filled": { name: "SpeechFilled", sizes: ["m", "l"] },
	square: { name: "Square", sizes: ["s", "l"] },
	"square--filled": { name: "SquareFilled", sizes: ["s", "l"] },
	"square-dashed": { name: "SquareDashed", sizes: ["s", "m", "l"] },
	star: { name: "Star", sizes: ["m", "l"] },
	"star--filled": { name: "StarFilled", sizes: ["m", "l"] },
	starbursts: { name: "Starbursts", sizes: ["l"] },
	"starbursts--filled": { name: "StarburstsFilled", sizes: ["l"] },
	stop: { name: "Stop", sizes: ["m", "l"] },
	"stop--filled": { name: "StopFilled", sizes: ["m", "l"] },
	store: { name: "Store", sizes: ["l"] },
	"store--filled": { name: "StoreFilled", sizes: ["l"] },
	stream: { name: "Stream", sizes: ["m", "l"] },
	"stream--filled": { name: "StreamFilled", sizes: ["m", "l"] },
	"stream-deck-key": { name: "StreamDeckKey", sizes: ["s", "m", "l"] },
	"stream-deck-key--filled": { name: "StreamDeckKeyFilled", sizes: ["s", "m", "l"] },
	"stream-deck-key-bottom": { name: "StreamDeckKeyBottom", sizes: ["s", "m", "l"] },
	"stream-deck-key-bottom--filled": { name: "StreamDeckKeyBottomFilled", sizes: ["s", "m", "l"] },
	"stream-deck-key-middle": { name: "StreamDeckKeyMiddle", sizes: ["s", "m", "l"] },
	"stream-deck-key-middle--filled": { name: "StreamDeckKeyMiddleFilled", sizes: ["s", "m", "l"] },
	"stream-deck-key-top": { name: "StreamDeckKeyTop", sizes: ["s", "m", "l"] },
	"stream-deck-key-top--filled": { name: "StreamDeckKeyTopFilled", sizes: ["s", "m", "l"] },
	"stream-deck-mini": { name: "StreamDeckMini", sizes: ["l"] },
	"stream-deck-mini--filled": { name: "StreamDeckMiniFilled", sizes: ["l"] },
	"stream-deck-mk2": { name: "StreamDeckMk2", sizes: ["l"] },
	"stream-deck-mk2--filled": { name: "StreamDeckMk2Filled", sizes: ["l"] },
	"stream-deck-neo": { name: "StreamDeckNeo", sizes: ["l"] },
	"stream-deck-neo--filled": { name: "StreamDeckNeoFilled", sizes: ["l"] },
	"stream-deck-pedal": { name: "StreamDeckPedal", sizes: ["l"] },
	"stream-deck-pedal--filled": { name: "StreamDeckPedalFilled", sizes: ["l"] },
	"stream-deck-plus": { name: "StreamDeckPlus", sizes: ["l"] },
	"stream-deck-plus--filled": { name: "StreamDeckPlusFilled", sizes: ["l"] },
	"stream-deck-virtual": { name: "StreamDeckVirtual", sizes: ["m"] },
	"stream-off": { name: "StreamOff", sizes: ["l"] },
	"stream-off--filled": { name: "StreamOffFilled", sizes: ["l"] },
	"stream-switch-to": { name: "StreamSwitchTo", sizes: ["l"] },
	"stream-switch-to--filled": { name: "StreamSwitchToFilled", sizes: ["l"] },
	strikethrough: { name: "Strikethrough", sizes: ["m", "l"] },
	subscription: { name: "Subscription", sizes: ["m"] },
	"subscription--filled": { name: "SubscriptionFilled", sizes: ["m"] },
	subtract: { name: "Subtract", sizes: ["m", "l"] },
	"subtract-circle": { name: "SubtractCircle", sizes: ["l"] },
	"subtract-circle--filled": { name: "SubtractCircleFilled", sizes: ["l"] },
	sync: { name: "Sync", sizes: ["l"] },
	system: { name: "System", sizes: ["m"] },
	"system--filled": { name: "SystemFilled", sizes: ["m"] },
	tag: { name: "Tag", sizes: ["m", "l"] },
	"tag--filled": { name: "TagFilled", sizes: ["m", "l"] },
	tap: { name: "Tap", sizes: ["l"] },
	"tap-double": { name: "TapDouble", sizes: ["l"] },
	"tap-hold": { name: "TapHold", sizes: ["l"] },
	temperature: { name: "Temperature", sizes: ["l"] },
	"temperature--filled": { name: "TemperatureFilled", sizes: ["l"] },
	"temperature-cool": { name: "TemperatureCool", sizes: ["l"] },
	"temperature-cool--filled": { name: "TemperatureCoolFilled", sizes: ["l"] },
	"temperature-warm": { name: "TemperatureWarm", sizes: ["l"] },
	"temperature-warm--filled": { name: "TemperatureWarmFilled", sizes: ["l"] },
	template: { name: "Template", sizes: ["l"] },
	"template--filled": { name: "TemplateFilled", sizes: ["l"] },
	terminal: { name: "Terminal", sizes: ["m", "l"] },
	"terminal--filled": { name: "TerminalFilled", sizes: ["m", "l"] },
	"test-tube": { name: "TestTube", sizes: ["m", "l"] },
	text: { name: "Text", sizes: ["l"] },
	"text-align-center": { name: "TextAlignCenter", sizes: ["l"] },
	"text-align-left": { name: "TextAlignLeft", sizes: ["l"] },
	"text-align-right": { name: "TextAlignRight", sizes: ["l"] },
	"text-down-to-bottom": { name: "TextDownToBottom", sizes: ["l"] },
	"text-line-spacing": { name: "TextLineSpacing", sizes: ["l"] },
	"text-line-spacing-set": { name: "TextLineSpacingSet", sizes: ["l"] },
	"text-next": { name: "TextNext", sizes: ["l"] },
	"text-previous": { name: "TextPrevious", sizes: ["l"] },
	"text-set": { name: "TextSet", sizes: ["l"] },
	"text-size": { name: "TextSize", sizes: ["l"] },
	"text-size-decrease": { name: "TextSizeDecrease", sizes: ["l"] },
	"text-size-increase": { name: "TextSizeIncrease", sizes: ["l"] },
	"text-size-set": { name: "TextSizeSet", sizes: ["l"] },
	"text-up-to-top": { name: "TextUpToTop", sizes: ["l"] },
	"thumb-down": { name: "ThumbDown", sizes: ["l"] },
	"thumb-down--filled": { name: "ThumbDownFilled", sizes: ["l"] },
	"thumb-up": { name: "ThumbUp", sizes: ["l"] },
	"thumb-up--filled": { name: "ThumbUpFilled", sizes: ["l"] },
	time: { name: "Time", sizes: ["s", "l"] },
	"time--filled": { name: "TimeFilled", sizes: ["s", "l"] },
	"time-delay": { name: "TimeDelay", sizes: ["l"] },
	"time-history": { name: "TimeHistory", sizes: ["m", "l"] },
	timer: { name: "Timer", sizes: ["l"] },
	"timer--filled": { name: "TimerFilled", sizes: ["l"] },
	tint: { name: "Tint", sizes: ["l"] },
	"tint--filled": { name: "TintFilled", sizes: ["l"] },
	token: { name: "Token", sizes: ["m", "l"] },
	"token--filled": { name: "TokenFilled", sizes: ["m", "l"] },
	train: { name: "Train", sizes: ["l"] },
	"train--filled": { name: "TrainFilled", sizes: ["l"] },
	transition: { name: "Transition", sizes: ["m", "l"] },
	"transition--filled": { name: "TransitionFilled", sizes: ["m", "l"] },
	trash: { name: "Trash", sizes: ["m", "l"] },
	"trash--filled": { name: "TrashFilled", sizes: ["m", "l"] },
	triangle: { name: "Triangle", sizes: ["l"] },
	"triangle--filled": { name: "TriangleFilled", sizes: ["l"] },
	"tumble-dry-no": { name: "TumbleDryNo", sizes: ["m"] },
	underline: { name: "Underline", sizes: ["m", "l"] },
	undo: { name: "Undo", sizes: ["l"] },
	"unordered-list": { name: "UnorderedList", sizes: ["m", "l"] },
	upload: { name: "Upload", sizes: ["m", "l"] },
	usb: { name: "Usb", sizes: ["m", "l"] },
	verified: { name: "Verified", sizes: ["s", "l"] },
	"verified--filled": { name: "VerifiedFilled", sizes: ["s", "l"] },
	video: { name: "Video", sizes: ["m", "l"] },
	"video--filled": { name: "VideoFilled", sizes: ["m", "l"] },
	view: { name: "View", sizes: ["m", "l"] },
	"view--filled": { name: "ViewFilled", sizes: ["m", "l"] },
	"view-hidden": { name: "ViewHidden", sizes: ["m"] },
	"view-off": { name: "ViewOff", sizes: ["m", "l"] },
	"view-off--filled": { name: "ViewOffFilled", sizes: ["m", "l"] },
	"voice-sync": { name: "VoiceSync", sizes: ["l"] },
	"voice-sync--filled": { name: "VoiceSyncFilled", sizes: ["l"] },
	"voice-tune": { name: "VoiceTune", sizes: ["m", "l"] },
	"voice-tune--filled": { name: "VoiceTuneFilled", sizes: ["m", "l"] },
	volume: { name: "Volume", sizes: ["m", "l"] },
	"volume--filled": { name: "VolumeFilled", sizes: ["m", "l"] },
	"volume-mixer": { name: "VolumeMixer", sizes: ["l"] },
	"volume-mixer--filled": { name: "VolumeMixerFilled", sizes: ["l"] },
	"volume-muted": { name: "VolumeMuted", sizes: ["m", "l"] },
	"volume-muted--filled": { name: "VolumeMutedFilled", sizes: ["m", "l"] },
	volume1: { name: "Volume1", sizes: ["m", "l"] },
	"volume1--filled": { name: "Volume1Filled", sizes: ["m", "l"] },
	volume2: { name: "Volume2", sizes: ["m", "l"] },
	"volume2--filled": { name: "Volume2Filled", sizes: ["m", "l"] },
	warning: { name: "Warning", sizes: ["s", "m", "l"] },
	"warning--filled": { name: "WarningFilled", sizes: ["s", "m", "l"] },
	wave: { name: "Wave", sizes: ["m", "l"] },
	"wave-dx": { name: "WaveDx", sizes: ["l"] },
	"wave-dx--filled": { name: "WaveDxFilled", sizes: ["l"] },
	"wave-mic": { name: "WaveMic", sizes: ["l"] },
	"wave-mic--filled": { name: "WaveMicFilled", sizes: ["l"] },
	"wave-neo": { name: "WaveNeo", sizes: ["l"] },
	"wave-neo--filled": { name: "WaveNeoFilled", sizes: ["l"] },
	"wave-xlr": { name: "WaveXlr", sizes: ["l"] },
	"wave-xlr--filled": { name: "WaveXlrFilled", sizes: ["l"] },
	weather: { name: "Weather", sizes: ["m", "l"] },
	"weather--filled": { name: "WeatherFilled", sizes: ["m", "l"] },
	webcam: { name: "Webcam", sizes: ["l"] },
	"webcam--filled": { name: "WebcamFilled", sizes: ["l"] },
	widget: { name: "Widget", sizes: ["m", "l"] },
	"widget--filled": { name: "WidgetFilled", sizes: ["m", "l"] },
	wifi: { name: "Wifi", sizes: ["l"] },
	"wifi-off": { name: "WifiOff", sizes: ["l"] },
	wifi1: { name: "Wifi1", sizes: ["l"] },
	wifi2: { name: "Wifi2", sizes: ["l"] },
	wifi3: { name: "Wifi3", sizes: ["l"] },
	window: { name: "Window", sizes: ["s", "m", "l"] },
	"window--filled": { name: "WindowFilled", sizes: ["s", "m", "l"] },
	"window-check": { name: "WindowCheck", sizes: ["l"] },
	"window-check--filled": { name: "WindowCheckFilled", sizes: ["l"] },
	"window-foreground": { name: "WindowForeground", sizes: ["s", "m", "l"] },
	"window-foreground--filled": { name: "WindowForegroundFilled", sizes: ["s", "m", "l"] },
	"window-to-prompter": { name: "WindowToPrompter", sizes: ["l"] },
	"window-to-prompter--filled": { name: "WindowToPrompterFilled", sizes: ["l"] },
	wrench: { name: "Wrench", sizes: ["l"] },
	"wrench--filled": { name: "WrenchFilled", sizes: ["l"] },
	xlr: { name: "Xlr", sizes: ["m", "l"] },
	"xlr--filled": { name: "XlrFilled", sizes: ["m", "l"] },
	"zoom-in": { name: "ZoomIn", sizes: ["l"] },
	"zoom-in--filled": { name: "ZoomInFilled", sizes: ["l"] },
	"zoom-out": { name: "ZoomOut", sizes: ["l"] },
	"zoom-out--filled": { name: "ZoomOutFilled", sizes: ["l"] },
} as const;
